import { SCIENTIFIC_THINKING_ENGINE_VERSION, type KnowledgeSupport, type ScientificThinkingInput } from "../types";

export const makeThinkingInput = (overrides: Partial<ScientificThinkingInput> = {}): ScientificThinkingInput => ({
  contractVersion: SCIENTIFIC_THINKING_ENGINE_VERSION,
  requestId: "scientific-thinking-request:test",
  originalExpression: "Je pense que le no-reflow après stenting est lié aux lésions microvasculaires.",
  validatedReformulation: "Je pense que le no-reflow après stenting est lié aux lésions microvasculaires.",
  language: "fr",
  scientificIntent: { intentRef: "validated-scientific-intent:test", userExpertise: "UNKNOWN", sourceJourney: "FORMALIZE_IDEA" },
  researchContext: { sessionId: "test-session", contextVersion: 1, researchProjectId: null, previousDecisionIds: [] },
  scientificObjectTerms: ["no-reflow", "lésions microvasculaires"],
  resolvedConcepts: [
    { conceptId: "concept:no-reflow", label: "no-reflow", status: "RESOLVED" },
    { conceptId: "concept:microvascular", label: "lésions microvasculaires", status: "RESOLVED" },
  ],
  relations: ["relation ou dépendance à examiner", "relation temporelle déclarée"],
  population: [],
  pathologyOrCondition: [],
  phenomena: ["no-reflow", "lésions microvasculaires"],
  outcomes: [],
  methodsMentioned: [],
  scientificPurpose: ["examiner une association"],
  context: ["après stenting"],
  missingInformation: [],
  projectUnknowns: [],
  contradictions: [],
  safetyFlags: [],
  information: { explicit: ["phenomenon:no-reflow", "context:après stenting"], interpreted: ["relation:atteinte microvasculaire"] },
  knowledge: {
    ownerResultRef: null,
    resultId: null,
    resultRevision: null,
    resultDigest: null,
    coverageStatus: "NO_MATCH",
    support: "UNSUPPORTED" as KnowledgeSupport,
    sourceIds: [],
    assertionRefs: [],
    documentaryStatementRefs: [],
    evidenceRefs: [],
    applicability: [],
    contradictionRefs: [],
    contradictions: [],
    gapRefs: [],
    gapCodes: ["NO_ASSERTION_MATCH"],
    reasoningStatements: [],
    controversies: [],
    gaps: [],
    unresolvedConcepts: [],
    limitations: [],
  },
  ...overrides,
});
