import { P4R_CONSOLIDATED_AT } from "./constants.mjs";

const pubmed = (pmid) => `https://pubmed.ncbi.nlm.nih.gov/${pmid}/`;
const pmc = (pmcid) => pmcid ? `https://pmc.ncbi.nlm.nih.gov/articles/${pmcid}/` : null;

const record = ({ pmid, title, authors, journal, publicationDate, volume, issue, pages, doi, pmcid = null, publicationTypes = [], officialFullTextUrl = null }) => Object.freeze({
  pmid,
  title,
  authors: Object.freeze(authors),
  journal,
  publicationDate,
  volume,
  issue,
  pages,
  doi,
  pmcid,
  publicationTypes: Object.freeze(publicationTypes),
  officialMetadataUrl: pubmed(pmid),
  officialFullTextUrl: officialFullTextUrl ?? pmc(pmcid),
  metadataAuthority: "NCBI_PUBMED_ESUMMARY_V2",
  metadataVerifiedAt: P4R_CONSOLIDATED_AT,
});

export const officialBibliographyByPmid = Object.freeze(Object.fromEntries([
  record({ pmid: "15236377", title: "Modified Look-Locker inversion recovery (MOLLI) for high-resolution T1 mapping of the heart", authors: ["Messroghli DR", "Radjenovic A", "Kozerke S", "Higgins DM", "Sivananthan MU", "Ridgway JP"], journal: "Magnetic Resonance in Medicine", publicationDate: "2004-07-01", volume: "52", issue: "1", pages: "141-146", doi: "10.1002/mrm.20110", publicationTypes: ["Journal Article"] }),
  record({ pmid: "21092095", title: "Shortened Modified Look-Locker Inversion recovery (ShMOLLI) for clinical myocardial T1-mapping at 1.5 and 3 T within a 9 heartbeat breathhold", authors: ["Piechnik SK", "Ferreira VM", "Dall'Armellina E", "Cochlin LE", "Greiser A", "Neubauer S", "Robson MD"], journal: "Journal of Cardiovascular Magnetic Resonance", publicationDate: "2010-11-19", volume: "12", issue: "1", pages: "69", doi: "10.1186/1532-429X-12-69", pmcid: "PMC3001433", publicationTypes: ["Journal Article"] }),
  record({ pmid: "22771879", title: "Interstitial myocardial fibrosis assessed as extracellular volume fraction with low-radiation-dose cardiac CT", authors: ["Nacif MS", "Kawel N", "Lee JJ", "Chen X", "Yao J", "Zavodni A", "Sibley CT", "Lima JA", "Liu S", "Bluemke DA"], journal: "Radiology", publicationDate: "2012-09-01", volume: "264", issue: "3", pages: "876-883", doi: "10.1148/radiol.12112458", pmcid: "PMC3426854", publicationTypes: ["Journal Article"] }),
  record({ pmid: "22963517", title: "Extracellular volume fraction mapping in the myocardium, part 1: evaluation of an automated method", authors: ["Kellman P", "Wilson JR", "Xue H", "Ugander M", "Arai AE"], journal: "Journal of Cardiovascular Magnetic Resonance", publicationDate: "2012-09-10", volume: "14", issue: "1", pages: "63", doi: "10.1186/1532-429X-14-63", pmcid: "PMC3441905", publicationTypes: ["Comparative Study", "Journal Article"] }),
  record({ pmid: "23553570", title: "Comprehensive validation of cardiovascular magnetic resonance techniques for the assessment of myocardial extracellular volume", authors: ["Miller CA", "Naish JH", "Bishop P", "Coutts G", "Clark D", "Zhao S", "Ray SG", "Yonan N", "Williams SG", "Flett AS", "Moon JC", "Greiser A", "Parker GJ", "Schmitt M"], journal: "Circulation: Cardiovascular Imaging", publicationDate: "2013-05-01", volume: "6", issue: "3", pages: "373-383", doi: "10.1161/CIRCIMAGING.112.000192", publicationTypes: ["Journal Article", "Validation Study"] }),
  record({ pmid: "23878282", title: "Measurement of myocardial extracellular volume fraction by using equilibrium contrast-enhanced CT: validation against histologic findings", authors: ["Bandula S", "White SK", "Flett AS", "Lawrence D", "Pugliese F", "Ashworth MT", "Punwani S", "Taylor SA", "Moon JC"], journal: "Radiology", publicationDate: "2013-11-01", volume: "269", issue: "2", pages: "396-403", doi: "10.1148/radiology.13130130", publicationTypes: ["Journal Article", "Validation Study"] }),
  record({ pmid: "23881866", title: "Saturation recovery single-shot acquisition (SASHA) for myocardial T1 mapping", authors: ["Chow K", "Flewitt JA", "Green JD", "Pagano JJ", "Friedrich MG", "Thompson RB"], journal: "Magnetic Resonance in Medicine", publicationDate: "2014-06-01", volume: "71", issue: "6", pages: "2082-2095", doi: "10.1002/mrm.24878", publicationTypes: ["Journal Article"] }),
  record({ pmid: "24124732", title: "Myocardial T1 mapping and extracellular volume quantification: a Society for Cardiovascular Magnetic Resonance (SCMR) and CMR Working Group of the European Society of Cardiology consensus statement", authors: ["Moon JC", "Messroghli DR", "Kellman P", "Piechnik SK", "Robson MD", "Ugander M", "Gatehouse PD", "Arai AE", "Friedrich MG", "Neubauer S", "Schulz-Menger J", "Schelbert EB", "Society for Cardiovascular Magnetic Resonance Imaging", "Cardiovascular Magnetic Resonance Working Group of the European Society of Cardiology"], journal: "Journal of Cardiovascular Magnetic Resonance", publicationDate: "2013-10-14", volume: "15", issue: "1", pages: "92", doi: "10.1186/1532-429X-15-92", pmcid: "PMC3854458", publicationTypes: ["Consensus Statement", "Review", "Journal Article"] }),
  record({ pmid: "24387626", title: "T1-mapping in the heart: accuracy and precision", authors: ["Kellman P", "Hansen MS"], journal: "Journal of Cardiovascular Magnetic Resonance", publicationDate: "2014-01-04", volume: "16", issue: "1", pages: "2", doi: "10.1186/1532-429X-16-2", pmcid: "PMC3927683", publicationTypes: ["Review", "Journal Article"] }),
  record({ pmid: "24702727", title: "Accuracy, precision, and reproducibility of four T1 mapping sequences: a head-to-head comparison of MOLLI, ShMOLLI, SASHA, and SAPPHIRE", authors: ["Roujol S", "Weingärtner S", "Foppa M", "Chow K", "Kawaji K", "Ngo LH", "Kellman P", "Manning WJ", "Thompson RB", "Nezafat R"], journal: "Radiology", publicationDate: "2014-09-01", volume: "272", issue: "3", pages: "683-689", doi: "10.1148/radiol.14140296", pmcid: "PMC4263641", publicationTypes: ["Comparative Study", "Evaluation Study", "Journal Article"] }),
  record({ pmid: "25384607", title: "Reference values for healthy human myocardium using a T1 mapping methodology: results from the International T1 Multicenter cardiovascular magnetic resonance study", authors: ["Dabir D", "Child N", "Kalra A", "Rogers T", "Gebker R", "Jabbour A", "Plein S", "Yu CY", "Otton J", "Kidambi A", "McDiarmid A", "Broadbent D", "Higgins DM", "Schnackenburg B", "Foote L", "Cummins C", "Nagel E", "Puntmann VO"], journal: "Journal of Cardiovascular Magnetic Resonance", publicationDate: "2014-10-21", volume: "16", issue: "1", pages: "69", doi: "10.1186/s12968-014-0069-x", pmcid: "PMC4203908", publicationTypes: ["Comparative Study", "Multicenter Study", "Journal Article"] }),
  record({ pmid: "25411195", title: "T1 mapping and survival in systemic light-chain amyloidosis", authors: ["Banypersad SM", "Fontana M", "Maestrini V", "Sado DM", "Captur G", "Petrie A", "Piechnik SK", "Whelan CJ", "Herrey AS", "Gillmore JD", "Lachmann HJ", "Wechalekar AD", "Hawkins PN", "Moon JC"], journal: "European Heart Journal", publicationDate: "2015-01-21", volume: "36", issue: "4", pages: "244-251", doi: "10.1093/eurheartj/ehu444", pmcid: "PMC4301598", publicationTypes: ["Journal Article"] }),
  record({ pmid: "27579699", title: "Shear-Wave Elastography Assessments of Quadriceps Stiffness Changes prior to, during and after Prolonged Exercise: A Longitudinal Study during an Extreme Mountain Ultra-Marathon", authors: ["Andonian P", "Viallon M", "Le Goff C", "de Bourguignon C", "Tourel C", "Morel J", "Giardini G", "Gergelé L", "Millet GP", "Croisille P"], journal: "PLOS ONE", publicationDate: "2016-08-31", volume: "11", issue: "8", pages: "e0161855", doi: "10.1371/journal.pone.0161855", pmcid: "PMC5007013", publicationTypes: ["Journal Article"] }),
  record({ pmid: "27771398", title: "Myocardial Extracellular Volume Estimation by CMR Predicts Functional Recovery Following Acute MI", authors: ["Kidambi A", "Motwani M", "Uddin A", "Ripley DP", "McDiarmid AK", "Swoboda PP", "Broadbent DA", "Musa TA", "Erhayiem B", "Leader J", "Croisille P", "Clarysse P", "Greenwood JP", "Plein S"], journal: "JACC: Cardiovascular Imaging", publicationDate: "2017-09-01", volume: "10", issue: "9", pages: "989-999", doi: "10.1016/j.jcmg.2016.06.015", pmcid: "PMC5593809", publicationTypes: ["Journal Article"] }),
  record({ pmid: "27878700", title: "Performance of native and contrast-enhanced T1 mapping to detect myocardial damage in patients with suspected myocarditis: a head-to-head comparison of different cardiovascular magnetic resonance techniques", authors: ["Nadjiri J", "Nieberler H", "Hendrich E", "Greiser A", "Will A", "Martinoff S", "Hadamitzky M"], journal: "The International Journal of Cardiovascular Imaging", publicationDate: "2017-04-01", volume: "33", issue: "4", pages: "539-547", doi: "10.1007/s10554-016-1029-3", publicationTypes: ["Comparative Study", "Journal Article"] }),
  record({ pmid: "27902782", title: "Correction: Shear-Wave Elastography Assessments of Quadriceps Stiffness Changes prior to, during and after Prolonged Exercise", authors: ["Andonian P", "Viallon M", "Le Goff C", "de Bourguignon C", "Tourel C", "Morel J", "Giardini G", "Gergelé L", "Millet GP", "Croisille P"], journal: "PLOS ONE", publicationDate: "2016-11-30", volume: "11", issue: "11", pages: "e0167668", doi: "10.1371/journal.pone.0167668", pmcid: "PMC5130261", publicationTypes: ["Published Erratum"] }),
  record({ pmid: "28980127", title: "Extracellular volume quantification by cardiac magnetic resonance imaging without hematocrit sampling: Ready for prime time?", authors: ["Kammerlander AA", "Duca F", "Binder C", "Aschauer S", "Zotter-Tufaro C", "Koschutnik M", "Marzluf BA", "Bonderman D", "Mascherbauer J"], journal: "Wiener klinische Wochenschrift", publicationDate: "2018-03-01", volume: "130", issue: "5-6", pages: "190-196", doi: "10.1007/s00508-017-1267-y", pmcid: "PMC5978936", publicationTypes: ["Journal Article"] }),
  record({ pmid: "28992817", title: "Clinical recommendations for cardiovascular magnetic resonance mapping of T1, T2, T2* and extracellular volume: A consensus statement by the SCMR endorsed by the EACVI", authors: ["Messroghli DR", "Moon JC", "Ferreira VM", "Grosse-Wortmann L", "He T", "Kellman P", "Mascherbauer J", "Nezafat R", "Salerno M", "Schelbert EB", "Taylor AJ", "Thompson R", "Ugander M", "van Heeswijk RB", "Friedrich MG"], journal: "Journal of Cardiovascular Magnetic Resonance", publicationDate: "2017-10-09", volume: "19", issue: "1", pages: "75", doi: "10.1186/s12968-017-0389-8", pmcid: "PMC5633041", publicationTypes: ["Consensus Statement", "Journal Article"] }),
  record({ pmid: "29415744", title: "Correction to: Clinical recommendations for cardiovascular magnetic resonance mapping of T1, T2, T2* and extracellular volume", authors: ["Messroghli DR", "Moon JC", "Ferreira VM", "Grosse-Wortmann L", "He T", "Kellman P", "Mascherbauer J", "Nezafat R", "Salerno M", "Schelbert EB", "Taylor AJ", "Thompson RB", "Ugander M", "van Heeswijk RB", "Friedrich MG"], journal: "Journal of Cardiovascular Magnetic Resonance", publicationDate: "2018-02-07", volume: "20", issue: "1", pages: "9", doi: "10.1186/s12968-017-0408-9", pmcid: "PMC5804075", publicationTypes: ["Published Erratum", "Journal Article"] }),
  record({ pmid: "30089499", title: "Extracellular volume fraction measurements derived from the longitudinal relaxation of blood-based synthetic hematocrit may lead to clinical errors in 3 T cardiovascular magnetic resonance", authors: ["Shang Y", "Zhang X", "Zhou X", "Wang J"], journal: "Journal of Cardiovascular Magnetic Resonance", publicationDate: "2018-08-09", volume: "20", issue: "1", pages: "56", doi: "10.1186/s12968-018-0475-6", pmcid: "PMC6083590", publicationTypes: ["Journal Article", "Validation Study"] }),
  record({ pmid: "30545455", title: "Cardiovascular Magnetic Resonance in Nonischemic Myocardial Inflammation: Expert Recommendations", authors: ["Ferreira VM", "Schulz-Menger J", "Holmvang G", "Kramer CM", "Carbone I", "Sechtem U", "Kindermann I", "Gutberlet M", "Cooper LT", "Liu P", "Friedrich MG"], journal: "Journal of the American College of Cardiology", publicationDate: "2018-12-18", volume: "72", issue: "24", pages: "3158-3176", doi: "10.1016/j.jacc.2018.09.072", publicationTypes: ["Review", "Journal Article"], officialFullTextUrl: "https://www.jacc.org/doi/10.1016/j.jacc.2018.09.072" }),
  record({ pmid: "31132211", title: "Detection of myocarditis using T1 and ECV mapping is not improved by early compared to late post-contrast imaging", authors: ["Lundin M", "Sörensson P", "Vishnevskaya L", "Maret E", "Kellman P", "Sigfridsson A", "Ugander M"], journal: "Clinical Physiology and Functional Imaging", publicationDate: "2019-11-01", volume: "39", issue: "6", pages: "384-392", doi: "10.1111/cpf.12588", publicationTypes: ["Comparative Study", "Journal Article"] }),
  record({ pmid: "32089132", title: "Standardized cardiovascular magnetic resonance imaging (CMR) protocols: 2020 update", authors: ["Kramer CM", "Barkhausen J", "Bucciarelli-Ducci C", "Flamm SD", "Kim RJ", "Nagel E"], journal: "Journal of Cardiovascular Magnetic Resonance", publicationDate: "2020-02-24", volume: "22", issue: "1", pages: "17", doi: "10.1186/s12968-020-00607-1", pmcid: "PMC7038611", publicationTypes: ["Practice Guideline", "Journal Article"] }),
  record({ pmid: "32160925", title: "Standardized image interpretation and post-processing in cardiovascular magnetic resonance - 2020 update", authors: ["Schulz-Menger J", "Bluemke DA", "Bremerich J", "Flamm SD", "Fogel MA", "Friedrich MG", "Kim RJ", "von Knobelsdorff-Brenkenhoff F", "Kramer CM", "Pennell DJ", "Plein S", "Nagel E"], journal: "Journal of Cardiovascular Magnetic Resonance", publicationDate: "2020-03-12", volume: "22", issue: "1", pages: "19", doi: "10.1186/s12968-020-00610-6", pmcid: "PMC7066763", publicationTypes: ["Practice Guideline", "Review", "Journal Article"] }),
  record({ pmid: "32375896", title: "T1 mapping performance and measurement repeatability: results from the multi-national T1 mapping standardization phantom program (T1MES)", authors: ["Captur G", "Bhandari A", "Brühl R", "Ittermann B", "Keenan KE", "Yang Y", "Eames RJ", "Benedetti G", "Torlasco C", "Ricketts L", "Boubertakh R", "Fatih N", "Greenwood JP", "Paulis LEM", "Lawton CB", "Bucciarelli-Ducci C", "Lamb HJ", "Steeds R", "Leung SW", "Berry C", "Valentin S", "Flett A", "de Lange C", "DeCobelli F", "Viallon M", "Croisille P", "Higgins DM", "Greiser A", "Pang W", "Hamilton-Craig C", "Strugnell WE", "Dresselaers T", "Barison A", "Dawson D", "Taylor AJ", "Mongeon FP", "Plein S", "Messroghli D", "Al-Mallah M", "Grieve SM", "Lombardi M", "Jang J", "Salerno M", "Chaturvedi N", "Kellman P", "Bluemke DA", "Nezafat R", "Gatehouse P", "Moon JC", "T1MES Consortium"], journal: "Journal of Cardiovascular Magnetic Resonance", publicationDate: "2020-05-07", volume: "22", issue: "1", pages: "31", doi: "10.1186/s12968-020-00613-3", pmcid: "PMC7204222", publicationTypes: ["Comparative Study", "Multicenter Study", "Journal Article"] }),
  record({ pmid: "37269267", title: "Cardiac Computed Tomography for Quantification of Myocardial Extracellular Volume Fraction: A Systematic Review and Meta-Analysis", authors: ["Han D", "Lin A", "Kuronuma K", "Gransar H", "Dey D", "Friedman JD", "Berman DS", "Tamarappoo BK"], journal: "JACC: Cardiovascular Imaging", publicationDate: "2023-10-01", volume: "16", issue: "10", pages: "1306-1317", doi: "10.1016/j.jcmg.2023.03.021", publicationTypes: ["Meta-Analysis", "Systematic Review", "Journal Article"], officialFullTextUrl: "https://www.jacc.org/doi/10.1016/j.jcmg.2023.03.021" }),
  record({ pmid: "37749293", title: "Myocardial extracellular volume quantification with computed tomography-current status and future outlook", authors: ["Cundari G", "Galea N", "Mergen V", "Alkadhi H", "Eberhard M"], journal: "Insights into Imaging", publicationDate: "2023-09-25", volume: "14", issue: "1", pages: "156", doi: "10.1186/s13244-023-01506-6", pmcid: "PMC10519917", publicationTypes: ["Review", "Journal Article"] }),
].map((item) => [item.pmid, item])));

export const officialBibliographyCount = Object.keys(officialBibliographyByPmid).length;

