import { describe, expect, it } from "vitest";
import { stableStringify } from "../migration/stable-json.mjs";
import { scientificAssertionRevisions, scientificEvidenceLinks } from "../scientific-corpus/assertions.mjs";
import { P4R_PUBLICATION_GUARDS, P4R_REVIEW_TYPE } from "./constants.mjs";
import { createP4RScientificSynthesis, p4rConceptReadiness, p4rInternalScientificProjections, p4rProjectionReadiness, p4rReadinessRules, p4rReadinessSummary, p4rScientificSyntheses, p4rSynthesisReadiness, queryConsolidatedScientificCorpus } from "./corpus.mjs";
import { contradictionSummary, p4rContradictionAssessments } from "./contradictions.mjs";
import { createGenericEnrichmentProtocol, domainSpecificExtensions, generalitySummary, genericScientificContracts, genericityFixtures, genericityResults, modalitySpecificExtensions, scientificExtensionPlan, specialtySpecificExtensions } from "./generality.mjs";
import { ontologyDecisionSummary, p4rOntologicalDecisions } from "./ontology.mjs";
import { assertionReviewSummary, consolidatedAssertionReviewDecisions, consolidatedAssertionRevisions, consolidatedEvidenceLinks, evidenceReviewMatrix } from "./review.mjs";
import { createP4Snapshot, p4Snapshot } from "./snapshot.mjs";
import { consolidatedSourceRecords, consolidatedSourceRevisionHistory, consolidatedSourceRevisions, sourceConsolidationSummary, supplementalCtSourceAudit } from "./sources.mjs";
import { ctEcvBranchAudit, metrologyContracts } from "./report.mjs";
import { validateAutomatedScientificReview, validateConsolidatedExtractions, validateConsolidatedScientificSources, validateP4RConsolidation, validateP4Snapshot, validateScientificGenerality } from "./validate.mjs";

describe("P4R ECV/T1 pilot consolidation", () => {
  it("creates a deterministic P4 snapshot", () => expect(stableStringify(createP4Snapshot())).toBe(stableStringify(p4Snapshot)));
  it("preserves all 27 P4 sources", () => expect(consolidatedSourceRevisions).toHaveLength(27));
  it("preserves all 58 P4 assertions", () => expect(consolidatedAssertionRevisions).toHaveLength(58));
  it("preserves all 84 P4 evidence links", () => expect(consolidatedEvidenceLinks).toHaveLength(84));
  it("retains both source revisions in history", () => expect(consolidatedSourceRevisionHistory).toHaveLength(54));
  it("links every source revision 2 to its P4 predecessor", () => expect(consolidatedSourceRecords.every((record) => record.after.supersedesRevisionId === record.before.revisionId)).toBe(true));
  it("completes metadata only from the registered PubMed authority", () => expect(consolidatedSourceRevisions.every((source) => source.metadata.metadataAuthority === "NCBI_PUBMED_ESUMMARY_V2")).toBe(true));
  it("keeps valid DOI values", () => expect(consolidatedSourceRevisions.every((source) => /^10\.\d{4,9}\//i.test(source.doi))).toBe(true));
  it("keeps valid PMID values", () => expect(consolidatedSourceRevisions.every((source) => /^\d{7,8}$/.test(source.pmid))).toBe(true));
  it("contains no abbreviated author placeholder", () => expect(consolidatedSourceRevisions.some((source) => source.authors.some((author) => /et al/i.test(author)))).toBe(false));
  it("completes every author list", () => expect(sourceConsolidationSummary.authorsCompleted).toBe(27));
  it("distinguishes full text from abstract only", () => expect([sourceConsolidationSummary.fullText, sourceConsolidationSummary.abstractOnly]).toEqual([21, 6]));
  it("upgrades exactly the two verified JACC full texts", () => expect(sourceConsolidationSummary.sourcesUpgradedFromAbstractOnly).toEqual(["30545455", "37269267"]));
  it("limits abstract-only evidence to an abstract locator", () => {
    const abstractIds = new Set(consolidatedSourceRevisions.filter((source) => source.metadata.abstractOnly).map((source) => source.revisionId));
    expect(consolidatedEvidenceLinks.filter((link) => abstractIds.has(link.sourceRevisionId)).every((link) => /PubMed|Abstract/i.test(link.locator))).toBe(true);
  });
  it("requires an exploitable locator", () => expect(consolidatedEvidenceLinks.every((link) => link.locator.split(/\s+/).length >= 3)).toBe(true));
  it("keeps extraction and assertion linkage compatible", () => expect(consolidatedEvidenceLinks.every((link) => link.extraction.assertionDerived === link.assertionRevisionId)).toBe(true));
  it("signals every derived interpretation", () => expect(consolidatedEvidenceLinks.filter((link) => link.extraction.interpretationLevel === "DERIVED_INTERPRETATION").every((link) => link.extraction.derivationSteps.length > 0)).toBe(true));
  it("never attributes a derived interpretation directly to authors", () => expect(consolidatedEvidenceLinks.filter((link) => link.extraction.interpretationLevel === "DERIVED_INTERPRETATION").every((link) => link.extraction.directAuthorStatement === false)).toBe(true));
  it("runs deterministic automated review", () => expect(stableStringify(consolidatedAssertionReviewDecisions)).toBe(stableStringify(consolidatedAssertionReviewDecisions)));
  it("uses the registered automated scientific review type", () => expect(consolidatedAssertionRevisions.every((assertion) => assertion.reviewType === P4R_REVIEW_TYPE)).toBe(true));
  it("claims no human review", () => expect(consolidatedAssertionReviewDecisions.every((decision) => decision.scientificHumanReview === null)).toBe(true));
  it("preserves SUPPORTS relations", () => expect(consolidatedEvidenceLinks.filter((link) => link.relationType === "SUPPORTS")).toHaveLength(57));
  it("does not promote MENTIONS", () => expect(consolidatedEvidenceLinks.filter((link) => link.relationType === "MENTIONS")).toHaveLength(2));
  it("preserves REFUTES", () => expect(consolidatedEvidenceLinks.filter((link) => link.relationType === "REFUTES")).toHaveLength(2));
  it("preserves QUALIFIES", () => expect(consolidatedEvidenceLinks.filter((link) => link.relationType === "QUALIFIES")).toHaveLength(17));
  it("preserves verified CORRECTS links", () => expect(consolidatedEvidenceLinks.filter((link) => link.relationType === "CORRECTS")).toHaveLength(2));
  it("records relation review even when no type changes", () => expect(evidenceReviewMatrix).toHaveLength(84));
  it("recalculates locators for the two upgraded sources", () => expect(assertionReviewSummary.locatorsRecalculated).toBe(6));
  it("passes assertions without documentary qualification", () => expect(assertionReviewSummary.passed).toBeGreaterThan(0));
  it("qualifies abstract-only and derived assertions", () => expect(assertionReviewSummary.qualified).toBeGreaterThan(0));
  it("keeps two assertions contested", () => expect(assertionReviewSummary.contested).toBe(2));
  it("keeps no active rejected assertion", () => expect(assertionReviewSummary.rejected).toBe(0));
  it("distinguishes contextual divergence from true contradiction", () => expect(contradictionSummary).toMatchObject({ trueContradictions: 0, contextDifferences: 1 }));
  it("preserves synthetic-hematocrit divergence", () => expect(p4rContradictionAssessments[0].decision).toBe("PRESERVE_DIVERGENCE_WITH_CONTEXT"));
  it("audits the CT-ECV branch", () => expect(ctEcvBranchAudit.representedBranches).toHaveLength(2));
  it("does not claim CT-ECV intersite reproducibility", () => expect(ctEcvBranchAudit.intersiteReproducibility).toBe("NOT_DOCUMENTED_IN_SELECTED_CORPUS"));
  it("examines supplemental CT sources without forcing them into the corpus", () => expect(supplementalCtSourceAudit.every((source) => source.decision === "EXAMINED_NOT_ADDED")).toBe(true));
  it("keeps repeatability distinct from reproducibility", () => expect(metrologyContracts.find((item) => item.term === "repeatability").distinctFrom).toContain("reproducibility"));
  it("keeps correlation distinct from agreement", () => expect(metrologyContracts.find((item) => item.term === "correlation").distinctFrom).toContain("agreement"));
  it("reassesses exactly six ontological decisions", () => expect(p4rOntologicalDecisions).toHaveLength(6));
  it("supports multi-role ontology", () => expect(ontologyDecisionSummary.multiRole).toBe(3));
  it("changes no historical identity class", () => expect(ontologyDecisionSummary.historicalClassesChanged).toBe(0));
  it("keeps out-of-scope ontology decisions explicitly deferred", () => expect(ontologyDecisionSummary.deferred).toBe(3));
  it("registers generic contracts without cardiology terms", () => expect(genericScientificContracts.some((contract) => /MOLLI|hematocrit|myocard/i.test(JSON.stringify(contract)))).toBe(false));
  it("isolates domain-specific extensions", () => expect(domainSpecificExtensions.every((extension) => extension.scope === "ECV_T1_PILOT")).toBe(true));
  it("isolates modality-specific extensions", () => expect(modalitySpecificExtensions.length).toBeGreaterThan(0));
  it("isolates specialty-specific extensions", () => expect(specialtySpecificExtensions.length).toBeGreaterThan(0));
  it("validates the ADC fixture without ECV dependencies", () => expect(genericityResults.find((result) => result.domain === "adc-diffusion").detectedPilotDependencies).toEqual([]));
  it("validates the Tmax fixture without ECV dependencies", () => expect(genericityResults.find((result) => result.domain === "ct-perfusion").detectedPilotDependencies).toEqual([]));
  it("validates DICOM without a biomarker model", () => expect(genericityFixtures.find((fixture) => fixture.domain === "dicom-standard").subjectType).toBe("TechnicalStandard"));
  it("validates segmentation without a clinical measurement", () => expect(genericityFixtures.find((fixture) => fixture.domain === "ai-segmentation").quantity).toBeNull());
  it("keeps every fixture outside the real corpus", () => expect(genericityFixtures.every((fixture) => fixture.fixtureOnly && !fixture.realCorpus)).toBe(true));
  it("passes all ten genericity fixtures", () => expect(generalitySummary.validFixtures).toBe(10));
  it("recalculates ten deterministic syntheses", () => expect(p4rScientificSyntheses).toHaveLength(10));
  it("regenerates an identical ECV synthesis digest", () => {
    const current = p4rScientificSyntheses.find((synthesis) => synthesis.key === "ecv");
    const regenerated = createP4RScientificSynthesis({ key: "ecv", label: "ECV — state of knowledge", query: { concept: "ecv" }, requiredDimensions: ["modality"] });
    expect(regenerated.deterministicDigest).toBe(current.deterministicDigest);
  });
  it("shows abstract-only sources in syntheses", () => expect(p4rScientificSyntheses.some((synthesis) => synthesis.abstractOnlySources.length > 0)).toBe(true));
  it("keeps context differences visible in syntheses", () => expect(p4rScientificSyntheses.some((synthesis) => synthesis.contradictions.length > 0)).toBe(true));
  it("keeps CT intersite missing data explicit", () => expect(p4rScientificSyntheses.find((synthesis) => synthesis.key === "ct-ecv").missingData).toContain("CT_ECV_INTERSITE_REPRODUCIBILITY_NOT_DOCUMENTED"));
  it("recalculates seven-dimensional readiness", () => expect(Object.keys(p4rReadinessSummary.concepts)).toHaveLength(7));
  it("does not use human review as the sole editorial blocker", () => expect(p4rReadinessRules.editorialProjectionReady.blockers).not.toContain("NO_SCIENTIFIC_HUMAN_REVIEW"));
  it("keeps public readiness false", () => expect(p4rReadinessSummary.publicPublicationReady).toBe(false));
  it("keeps readiness dimensions independent", () => expect(p4rReadinessSummary.projections.editorialProjectionReady).toBeGreaterThan(p4rReadinessSummary.projections.publicPublicationReady));
  it("creates a generic 18-step enrichment protocol", () => expect(createGenericEnrichmentProtocol("adc-diffusion").steps).toHaveLength(18));
  it("creates deterministic domain protocols", () => expect(createGenericEnrichmentProtocol("ct-perfusion").deterministicDigest).toBe(createGenericEnrichmentProtocol("ct-perfusion").deterministicDigest));
  it("starts no future domain enrichment", () => expect(scientificExtensionPlan.every((domain) => !Object.hasOwn(domain, "assertions"))).toBe(true));
  it("proposes eight diverse future domains", () => expect(scientificExtensionPlan).toHaveLength(8));
  it("keeps all 12 projections internal", () => expect(p4rInternalScientificProjections).toHaveLength(12));
  it("creates no public prose", () => expect(p4rInternalScientificProjections.every((projection) => projection.prose === null)).toBe(true));
  it("routes no projection", () => expect(p4rInternalScientificProjections.every((projection) => projection.route === null)).toBe(true));
  it("indexes no projection", () => expect(p4rInternalScientificProjections.every((projection) => !projection.indexable && !projection.inSitemap)).toBe(true));
  it("preserves every P4R publication guard", () => expect(p4rInternalScientificProjections.every((projection) => Object.entries(P4R_PUBLICATION_GUARDS).every(([key, value]) => projection[key] === value))).toBe(true));
  it("never performs a statistical meta-analysis", () => expect(p4rScientificSyntheses.every((synthesis) => !synthesis.statisticalMetaAnalysisPerformed)).toBe(true));
  it("keeps compound queries deterministic", () => expect(queryConsolidatedScientificCorpus({ concept: "ecv", modality: "ct" }).deterministicDigest).toBe(queryConsolidatedScientificCorpus({ concept: "ecv", modality: "ct" }).deterministicDigest));
  it("validates the snapshot layer", () => expect(validateP4Snapshot().valid).toBe(true));
  it("validates the source layer", () => expect(validateConsolidatedScientificSources().valid).toBe(true));
  it("validates the extraction layer", () => expect(validateConsolidatedExtractions().valid).toBe(true));
  it("validates the review layer", () => expect(validateAutomatedScientificReview().valid).toBe(true));
  it("validates the generic method", () => expect(validateScientificGenerality().valid).toBe(true));
  it("validates the complete P4R gate without inspecting Git", () => expect(validateP4RConsolidation({ inspectGit: false }).valid).toBe(true));
  it("keeps source, assertion, and evidence counts aligned with P4", () => expect([sourceConsolidationSummary.preservedP4Sources, assertionReviewSummary.total, assertionReviewSummary.evidenceLinks]).toEqual([27, 58, 84]));
  it("keeps original P4 arrays unchanged", () => expect([scientificAssertionRevisions.length, scientificEvidenceLinks.length]).toEqual([58, 84]));
  it("marks editorial readiness as future eligibility only", () => expect(p4rProjectionReadiness.every((item) => item.editorialProjectionReady.justification.includes("Eligible") || item.editorialProjectionReady.justification.includes("eligible"))).toBe(true));
  it("keeps synthesis and projection public readiness false", () => expect([...p4rSynthesisReadiness, ...p4rProjectionReadiness].every((item) => !item.publicPublicationReady.ready)).toBe(true));
  it("keeps concept public readiness false", () => expect(p4rConceptReadiness.every((item) => !item.publicPublicationReady.ready)).toBe(true));
});
