import type { LlmOperationClass } from "./types";

export const LLM_POLICY_VERSION = "KE-001-Q-v1.0" as const;

export const LLM_OPERATION_POLICY = Object.freeze({
  BUILD_REQUEST: "DETERMINISTIC",
  MINIMIZE_CONTEXT: "DETERMINISTIC",
  RESOLVE_GOVERNED_CONCEPT: "DETERMINISTIC",
  PROPOSE_ALIAS: "LLM_PROPOSAL_ONLY",
  SELECT_PROVIDER: "FORBIDDEN",
  BUILD_QUERY_PLAN: "DETERMINISTIC",
  RETRIEVE_CORPUS: "DETERMINISTIC",
  ASSESS_APPLICABILITY: "DETERMINISTIC",
  NORMALIZE_ASSERTION: "DETERMINISTIC",
  RESOLVE_CONFLICT: "HUMAN_REQUIRED",
  BUILD_STRUCTURED_SYNTHESIS: "DETERMINISTIC",
  WRITE_NARRATIVE_PROJECTION: "LLM_ALLOWED",
  SELECT_BEST_BIOMARKER: "FORBIDDEN",
  INTERPRET_PATIENT_VALUE: "FORBIDDEN",
} satisfies Record<string, LlmOperationClass>);

export type LlmOperation = keyof typeof LLM_OPERATION_POLICY;
export const classifyLlmOperation = (operation: LlmOperation) => LLM_OPERATION_POLICY[operation];

