import { execFileSync } from "node:child_process";
import { describe, expect, it } from "vitest";
import { stableStringify } from "../migration/stable-json.mjs";
import { inspectProtectedSurfaces } from "../scientific-corpus/protected-surfaces.mjs";
import { multidomainAssertionRevisions, multidomainAssertionReviewDecisions, multidomainEvidenceLinks } from "./assertions.mjs";
import { createP4RBaselineSnapshot, p4rBaselineSnapshot } from "./baseline.mjs";
import { conceptByKey, multidomainConcepts } from "./concepts.mjs";
import { multidomainContradictionAssessments } from "./contradictions.mjs";
import { P5_DOMAIN_IDS, P5_PUBLICATION_GUARDS } from "./constants.mjs";
import { confirmedGenericInvariants, genericContractModifications, p5DomainSpecificExtensions, p5GeneralitySummary, residualEcvBiasAudit } from "./generality.mjs";
import { scientificDomainManifests } from "./manifests.mjs";
import { contextualThresholdRecords, metrologyDistinctions, multidomainMeasurementRecords } from "./measurements.mjs";
import { multidomainInternalProjections } from "./projections.mjs";
import { executeMandatoryMultidomainQueries, queryScientificMultidomain } from "./query.mjs";
import { multidomainDomainReadiness, multidomainProjectionReadiness, multidomainReadinessSummary } from "./readiness.mjs";
import { multidomainSourceRevisions, multidomainSourceSummary } from "./sources.mjs";
import { createMultidomainSynthesis, multidomainScientificSyntheses, multidomainSynthesisDefinitions } from "./synthesis.mjs";
import { validateP4RBaselineForP5, validateScientificDomains, validateScientificMultidomain } from "./validate.mjs";
import { withoutAuthorizedProtectedChanges } from "../../test/p12-protected-surfaces.mjs";

const protectedState = inspectProtectedSurfaces({ root: process.cwd() });
const queries = executeMandatoryMultidomainQueries();
const concept = (key) => conceptByKey[key];
const assertion = (key) => multidomainAssertionRevisions.find((item) => item.stableId.endsWith(`:${key}`));

describe("P5 scientific multidomain wave", () => {
  it("preserves the deterministic P4R baseline", () => expect(validateP4RBaselineForP5().valid).toBe(true));
  it("regenerates an identical P4R baseline", () => expect(stableStringify(createP4RBaselineSnapshot())).toBe(stableStringify(p4rBaselineSnapshot)));
  it("preserves all 27 P4R sources", () => expect(p4rBaselineSnapshot.sourceRevisions).toHaveLength(27));
  it("preserves all 58 P4R assertions", () => expect(p4rBaselineSnapshot.assertionRevisions).toHaveLength(58));
  it("preserves all 84 P4R evidence links", () => expect(p4rBaselineSnapshot.evidenceLinks).toHaveLength(84));
  it("creates four valid domain manifests", () => expect(validateScientificDomains().valid).toBe(true));
  it("defines explicit domain boundaries", () => expect(scientificDomainManifests.every((item) => item.coreConcepts.length && item.boundaryConcepts.length && item.exclusions.length)).toBe(true));
  it("makes no manifest depend on ECV/T1", () => expect(scientificDomainManifests.every((item) => !item.ecvT1Dependency)).toBe(true));
  it("versions 38 retained real sources", () => expect(multidomainSourceRevisions).toHaveLength(38));
  it("links every retained source to an assertion", () => expect(multidomainSourceRevisions.every((source) => multidomainEvidenceLinks.some((link) => link.sourceRevisionId === source.revisionId))).toBe(true));
  it("examines 52 sources and records 14 rejections", () => expect([multidomainSourceSummary.externalExamined, multidomainSourceSummary.rejected]).toEqual([52, 14]));
  it("distinguishes full text from abstract only", () => expect([multidomainSourceSummary.fullText, multidomainSourceSummary.abstractOnly]).toEqual([29, 9]));
  it("keeps all DOI values valid", () => expect(multidomainSourceRevisions.every((item) => /^10\.\d{4,9}\//.test(item.doi))).toBe(true));
  it("keeps all PMID values valid", () => expect(multidomainSourceRevisions.every((item) => /^\d{7,8}$/.test(item.pmid))).toBe(true));
  it("does not invent abbreviated author placeholders", () => expect(multidomainSourceRevisions.some((item) => item.authors.some((author) => /^et al/i.test(author)))).toBe(false));
  it("creates only sourced concepts", () => expect(multidomainConcepts.every((item) => item.sourceRefs.length === 1)).toBe(true));
  it("creates 15 concepts per domain", () => expect(P5_DOMAIN_IDS.map((domainId) => multidomainConcepts.filter((item) => item.domainId === domainId).length)).toEqual([15, 15, 15, 15]));
  it("keeps assertions atomic", () => expect(multidomainAssertionRevisions.every((item) => item.statement.atomicConclusionCount === 1)).toBe(true));
  it("requires a source for every assertion", () => expect(multidomainAssertionRevisions.every((item) => item.sourceRefs.length > 0)).toBe(true));
  it("localizes every EvidenceLink", () => expect(multidomainEvidenceLinks.every((item) => item.locator && item.extraction.section && item.extraction.passage)).toBe(true));
  it("limits abstract-only evidence to PubMed abstract locators", () => {
    const ids = new Set(multidomainSourceRevisions.filter((item) => item.abstractOnly).map((item) => item.revisionId));
    expect(multidomainEvidenceLinks.filter((item) => ids.has(item.sourceRevisionId)).every((item) => /PubMed abstract/i.test(item.locator))).toBe(true);
  });
  it("does not promote MENTIONS as sole evidence", () => {
    const mention = multidomainEvidenceLinks.find((item) => item.relationType === "MENTIONS");
    expect(multidomainEvidenceLinks.some((item) => item.assertionRevisionId === mention.assertionRevisionId && item.relationType === "SUPPORTS")).toBe(true);
  });
  it("distinguishes ADC from DWI", () => expect([concept("adc-value").roles[0], concept("dwi").roles[0]]).toEqual(["DerivedMeasurement", "AcquisitionMethod"]));
  it("distinguishes ADC from restriction finding", () => expect(concept("diffusion-restriction").roles).toEqual(["Finding"]));
  it("contextualizes b-value with a sourced unit", () => expect(multidomainMeasurementRecords.find((item) => item.measurementId.endsWith(":b-value")).unit).toBe("s/mm²"));
  it("distinguishes Tmax from CBF", () => expect(concept("tmax").stableId).not.toBe(concept("cbf").stableId));
  it("distinguishes CBF from CBV", () => expect(concept("cbf").stableId).not.toBe(concept("cbv").stableId));
  it("requires complete context for perfusion thresholds", () => expect(contextualThresholdRecords.every((item) => item.context.population && item.context.algorithm && item.unit)).toBe(true));
  it("never marks a perfusion threshold universal", () => expect(contextualThresholdRecords.every((item) => !item.universal)).toBe(true));
  it("does not assume perfusion software equivalence", () => expect(multidomainContradictionAssessments.find((item) => item.domainId === "cerebral-perfusion").decision).toContain("SOFTWARE"));
  it("distinguishes LGE from MVO", () => expect(concept("lge-finding").stableId).not.toBe(concept("microvascular-obstruction").stableId));
  it("distinguishes MVO from intramyocardial hemorrhage", () => expect(concept("microvascular-obstruction").stableId).not.toBe(concept("intramyocardial-hemorrhage").stableId));
  it("keeps a finding distinct from a measurement", () => expect(concept("intramyocardial-hemorrhage").roles[0]).toBe("Finding"));
  it("classifies PSIR as a reconstruction method", () => expect(concept("psir").roles).toContain("ReconstructionMethod"));
  it("distinguishes spectral CT from photon-counting CT", () => expect(concept("spectral-ct").stableId).not.toBe(concept("photon-counting-ct").stableId));
  it("does not merge spectral technology implementations", () => expect(new Set(["dual-source-de", "rapid-kvp-switching", "dual-layer-detector"].map((key) => concept(key).stableId)).size).toBe(3));
  it("keeps iodine maps distinct from CT-ECV", () => expect(assertion("iodine-map-not-ct-ecv").predicate).toBe("IS_NOT"));
  it("leaves manufacturer context unknown when unreported", () => expect(assertion("vmi-energy-specific").context.dimensions.find((item) => item.dimension === "manufacturer").operator).toBe("UNKNOWN"));
  it("records platform only when a source-specific context exists", () => expect(assertion("intermanufacturer-variability").facets.platforms).toContain("MULTIMANUFACTURER_PHANTOM"));
  it("requires units for source-documented quantities", () => expect(multidomainMeasurementRecords.filter((item) => item.unitStatus === "SOURCE_DOCUMENTED").every((item) => item.unit)).toBe(true));
  it("contains only one explicitly sourced formula", () => expect(multidomainMeasurementRecords.filter((item) => item.formula).map((item) => item.formula)).toEqual(["MTT = CBV / CBF"]));
  it("invents no normal range", () => expect(multidomainMeasurementRecords.some((item) => Object.hasOwn(item, "referenceRange"))).toBe(false));
  it("keeps repeatability distinct from reproducibility", () => expect(metrologyDistinctions.find((item) => item.term === "repeatability").distinctFrom).toContain("reproducibility"));
  it("keeps correlation distinct from agreement", () => expect(metrologyDistinctions.find((item) => item.term === "correlation").distinctFrom).toContain("agreement"));
  it("preserves one evidence difference group per domain", () => expect(new Set(multidomainContradictionAssessments.map((item) => item.domainId)).size).toBe(4));
  it("does not resolve differences artificially", () => expect(multidomainContradictionAssessments.every((item) => !item.resolutionApplied)).toBe(true));
  it("contextualizes method differences", () => expect(multidomainContradictionAssessments.filter((item) => item.classification === "METHOD_DIFFERENCE")).toHaveLength(2));
  it("creates three syntheses per domain", () => expect(P5_DOMAIN_IDS.every((domainId) => multidomainScientificSyntheses.filter((item) => item.domainId === domainId).length === 3)).toBe(true));
  it("keeps syntheses deterministic", () => expect(multidomainSynthesisDefinitions.every((definition) => stableStringify(createMultidomainSynthesis(definition)) === stableStringify(multidomainScientificSyntheses.find((item) => item.key === definition.key)))).toBe(true));
  it("never calls a structured synthesis a meta-analysis", () => expect(multidomainScientificSyntheses.every((item) => !item.statisticalMetaAnalysisPerformed && item.synthesisType.includes("NOT_META_ANALYSIS"))).toBe(true));
  it("keeps compound queries deterministic", () => expect(queryScientificMultidomain({ domainId: "cerebral-perfusion", concept: "tmax" }).deterministicDigest).toBe(queryScientificMultidomain({ domainId: "cerebral-perfusion", concept: "tmax" }).deterministicDigest));
  it("returns all mandatory multidomain queries", () => expect(Object.values(queries).every((item) => item.applicableAssertions.length > 0)).toBe(true));
  it("makes missing data explicit", () => expect(queryScientificMultidomain({ domainId: "spectral-ct", concept: "absent-concept" }).dataMissing).toContain("NO_APPLICABLE_ASSERTION"));
  it("creates two internal projections per domain", () => expect(P5_DOMAIN_IDS.every((domainId) => multidomainInternalProjections.filter((item) => item.domainId === domainId).length === 2)).toBe(true));
  it("routes no projection", () => expect(multidomainInternalProjections.every((item) => item.route === null)).toBe(true));
  it("indexes no projection", () => expect(multidomainInternalProjections.every((item) => !item.indexable)).toBe(true));
  it("puts no projection in the sitemap", () => expect(multidomainInternalProjections.every((item) => !item.inSitemap)).toBe(true));
  it("renders no projection", () => expect(multidomainInternalProjections.every((item) => !item.rendered && item.prose === null)).toBe(true));
  it("preserves all publication guards", () => expect(multidomainInternalProjections.every((item) => Object.entries(P5_PUBLICATION_GUARDS).every(([key, value]) => item[key] === value))).toBe(true));
  it("calculates readiness independently", () => expect(multidomainReadinessSummary.readinessDimensionsCollapsed).toBe(false));
  it("allows internal editorial projection readiness", () => expect(multidomainDomainReadiness.every((item) => item.editorialProjectionReady.ready)).toBe(true));
  it("keeps public readiness blocked", () => expect([...multidomainDomainReadiness, ...multidomainProjectionReadiness].every((item) => !item.publicPublicationReady.ready)).toBe(true));
  it("confirms all 18 generic contracts across five domains", () => expect(confirmedGenericInvariants.every((item) => item.userDomains.length === 5)).toBe(true));
  it("keeps generic contracts free of ECV-specific terms", () => expect(confirmedGenericInvariants.some((item) => /hematocrit|molli|sasha|ecv formula/i.test(JSON.stringify(item)))).toBe(false));
  it("isolates domain-specific extensions", () => expect(p5DomainSpecificExtensions.every((item) => P5_DOMAIN_IDS.includes(item.domainId))).toBe(true));
  it("changes no generic contract", () => expect(genericContractModifications).toHaveLength(0));
  it("detects no residual ECV/T1 bias", () => expect(p5GeneralitySummary.residualEcvBiasDetected).toBe(false));
  it("imposes no hematocrit outside ECV/T1", () => expect(residualEcvBiasAudit.mandatoryHematocrit).toBe(false));
  it("claims no human scientific review", () => expect(multidomainAssertionReviewDecisions.every((item) => item.scientificHumanReview === null)).toBe(true));
  it("leaves public pages unchanged outside explicitly authorized product missions", () => expect(withoutAuthorizedProtectedChanges(protectedState.protectedChanges.filter((item) => item.surface === "PUBLIC_PAGES"))).toEqual([]));
  it("leaves public routes unchanged outside explicitly authorized product missions", () => expect(withoutAuthorizedProtectedChanges(protectedState.protectedChanges.filter((item) => item.surface === "PUBLIC_ROUTES"))).toEqual([]));
  it("leaves SEO unchanged outside explicitly authorized product missions", () => expect(withoutAuthorizedProtectedChanges(protectedState.protectedChanges.filter((item) => item.surface === "SEO"))).toEqual([]));
  it("leaves viewers unchanged", () => expect(protectedState.protectedChanges.filter((item) => item.surface === "VIEWERS")).toEqual([]));
  it("leaves PACS unchanged", () => expect(protectedState.protectedChanges.filter((item) => item.surface === "PACS")).toEqual([]));
  it("leaves Supabase unchanged", () => expect(protectedState.protectedChanges.filter((item) => item.surface === "SUPABASE")).toEqual([]));
  it("leaves editorial-engine unchanged", () => expect(protectedState.editorialEngineUnchanged).toBe(true));
  it("preserves the recorded P5 HEAD in repository history", () => expect(() => execFileSync("git", ["merge-base", "--is-ancestor", "857e94b6df88289b59de149fe8f77e84dbee9492", "HEAD"], { encoding: "utf8" })).not.toThrow());
  it("passes git diff check", () => expect(() => execFileSync("git", ["diff", "--check"], { encoding: "utf8" })).not.toThrow());
  it("validates the complete P5 gate without Git inspection", () => expect(validateScientificMultidomain({ inspectGit: false }).valid).toBe(true));
});
