import type { SemanticElementType } from "./types";

export type GoldSemanticTarget = { meaning: string; aliases: string[]; type: SemanticElementType; critical: boolean };
export type GoldSemanticRelation = { source: string; target: string; relationAliases: string[]; critical: boolean };
export type SemanticCompetenceCase = {
  caseId: string;
  split: "DEVELOPMENT_CASES" | "HOLDOUT_CASES";
  domain: string;
  turns: string[];
  gold: {
    requiredExplicitObjects: GoldSemanticTarget[];
    requiredRelations: GoldSemanticRelation[];
    acceptableInferences: string[];
    forbiddenInferences: string[];
    requiredAmbiguities: string[];
    optionalClarifications: string[];
    forbiddenClarifications: string[];
    expectedIntent: string;
    allowedRoutes: Array<"UNDERSTAND" | "FORMALIZE_IDEA" | "DESIGN_STUDY" | "DOCUMENT" | "REVIEW_REROUTE">;
    criticalSemanticElements: string[];
    correction?: { rejectedMeaning: string; activeMeaning: string };
    contextMustRetain?: string[];
  };
};

type ObjectSpec = [SemanticElementType, string, string[]?];
type RelationSpec = [string, string, string, string[]?];
type CaseSpec = {
  id: string; domain: string; turns: string[]; intent: string; routes: SemanticCompetenceCase["gold"]["allowedRoutes"];
  objects: ObjectSpec[]; relations?: RelationSpec[]; acceptable?: string[]; forbidden?: string[]; ambiguities?: string[];
  optionalQuestions?: string[]; forbiddenQuestions?: string[]; correction?: SemanticCompetenceCase["gold"]["correction"]; retain?: string[];
};

const makeCases = (split: SemanticCompetenceCase["split"], specs: CaseSpec[]): SemanticCompetenceCase[] => specs.map((spec) => ({
  caseId: spec.id,
  split,
  domain: spec.domain,
  turns: spec.turns,
  gold: {
    requiredExplicitObjects: spec.objects.map(([type, meaning, aliases = []]) => ({ meaning, aliases, type, critical: true })),
    requiredRelations: (spec.relations ?? []).map(([source, relation, target, aliases = []]) => ({ source, target, relationAliases: [relation, ...aliases], critical: true })),
    acceptableInferences: spec.acceptable ?? [],
    forbiddenInferences: spec.forbidden ?? [],
    requiredAmbiguities: spec.ambiguities ?? [],
    optionalClarifications: spec.optionalQuestions ?? [],
    forbiddenClarifications: spec.forbiddenQuestions ?? [],
    expectedIntent: spec.intent,
    allowedRoutes: spec.routes,
    criticalSemanticElements: spec.objects.map(([, meaning]) => meaning),
    correction: spec.correction,
    contextMustRetain: spec.retain,
  },
}));

export const DEVELOPMENT_CASES: SemanticCompetenceCase[] = makeCases("DEVELOPMENT_CASES", [
  { id: "SEM-D01", domain: "imagerie vasculaire", turns: ["Je voudrais évaluer la carotidienne via différentes modalités."], intent: "évaluer et comparer", routes: ["FORMALIZE_IDEA", "DESIGN_STUDY"], objects: [["ANATOMICAL_CONTEXT", "carotide", ["carotidienne"]], ["MODALITY", "modalités d'imagerie", ["différentes modalités"]]], relations: [["modalités d'imagerie", "COMPARE_FOR", "carotide"]], ambiguities: ["objet carotidien à évaluer"], optionalQuestions: ["plaque", "sténose", "paroi", "vulnérabilité"] },
  { id: "SEM-D02", domain: "cardiologie", turns: ["Je veux évaluer une stratégie de reperfusion avec mise en place d'un stent immédiat vs différé et quantifier les lésions à l'IRM."], intent: "comparer", routes: ["DESIGN_STUDY", "FORMALIZE_IDEA"], objects: [["SCIENTIFIC_INTENT", "évaluer"], ["INTERVENTION", "stent immédiat"], ["COMPARATOR", "stent différé"], ["MODALITY", "IRM"], ["SCIENTIFIC_OBJECT", "lésions"]], relations: [["stent immédiat", "COMPARES_WITH", "stent différé"], ["lésions", "MEASURED_BY", "IRM"]], acceptable: ["contexte coronaire aigu", "dommage myocardique", "taille d'infarctus", "obstruction microvasculaire", "œdème", "fonction ventriculaire"], forbidden: ["STEMI confirmé", "taille d'infarctus confirmée comme critère principal"] },
  { id: "SEM-D03", domain: "cardiologie", turns: ["Chez des patients présentant un STEMI antérieur, je veux comparer à 5 jours la taille d'infarctus mesurée en LGE entre stenting immédiat et différé, avec MVO en critère secondaire."], intent: "comparer", routes: ["DESIGN_STUDY"], objects: [["POPULATION", "patients avec STEMI antérieur"], ["TIMING", "5 jours"], ["ENDPOINT", "taille d'infarctus"], ["METHOD", "LGE"], ["INTERVENTION", "stenting immédiat"], ["COMPARATOR", "stenting différé"], ["ENDPOINT", "MVO"]], relations: [["stenting immédiat", "COMPARES_WITH", "stenting différé"], ["taille d'infarctus", "MEASURED_BY", "LGE"]], forbiddenQuestions: ["population", "timing", "comparateur", "modalité", "critère principal"] },
  { id: "SEM-D04", domain: "imagerie quantitative", turns: ["comparer CT et IRM cardiaque"], intent: "comparer", routes: ["UNDERSTAND", "FORMALIZE_IDEA"], objects: [["MODALITY", "CT"], ["MODALITY", "IRM cardiaque"]], relations: [["CT", "COMPARES_WITH", "IRM cardiaque"]], ambiguities: ["dimension de comparaison"] },
  { id: "SEM-D05", domain: "cardiologie", turns: ["je veux étudier la fibrose"], intent: "étudier", routes: ["FORMALIZE_IDEA"], objects: [["SCIENTIFIC_OBJECT", "fibrose"]], ambiguities: ["organe", "finalité", "population"] },
  { id: "SEM-D06", domain: "cardiologie", turns: ["je veux mesurer la fibrose myocardique diffuse chez Fabry par ECV"], intent: "mesurer", routes: ["DESIGN_STUDY", "FORMALIZE_IDEA"], objects: [["SCIENTIFIC_OBJECT", "fibrose myocardique diffuse"], ["CONDITION", "Fabry"], ["BIOMARKER", "ECV"]], relations: [["ECV", "MEASURES", "fibrose myocardique diffuse"]], forbiddenQuestions: ["organe", "pathologie", "biomarqueur"] },
  { id: "SEM-D07", domain: "imagerie quantitative", turns: ["est-ce que le T1 est meilleur que le T2 ?"], intent: "comparer", routes: ["UNDERSTAND", "FORMALIZE_IDEA"], objects: [["BIOMARKER", "T1"], ["BIOMARKER", "T2"]], relations: [["T1", "COMPARES_WITH", "T2"]], ambiguities: ["critère de meilleur"] },
  { id: "SEM-D08", domain: "oncologie", turns: ["je veux regarder si les lésions diminuent après traitement"], intent: "mesurer un changement", routes: ["FORMALIZE_IDEA", "DESIGN_STUDY"], objects: [["SCIENTIFIC_OBJECT", "lésions"], ["INTERVENTION", "traitement"], ["EXPECTED_DIRECTION", "diminution"]], relations: [["lésions", "CHANGES_AFTER", "traitement"]], ambiguities: ["définition des lésions", "temporalité"] },
  { id: "SEM-D09", domain: "financement", turns: ["fais-moi un protocole PHRC multicentrique sur la myocardite"], intent: "document et étude", routes: ["DOCUMENT", "DESIGN_STUDY"], objects: [["CONDITION", "myocardite"], ["STUDY_DESIGN", "multicentrique"], ["SCIENTIFIC_INTENT", "protocole PHRC"]], ambiguities: ["question scientifique", "population", "critères"] },
  { id: "SEM-D10", domain: "neuroradiologie", turns: ["Comparer DSC et ASL pour le CBF tumoral"], intent: "comparer", routes: ["UNDERSTAND", "DESIGN_STUDY"], objects: [["METHOD", "DSC"], ["METHOD", "ASL"], ["BIOMARKER", "CBF tumoral"]], relations: [["DSC", "COMPARES_WITH", "ASL"], ["DSC", "MEASURES", "CBF tumoral"]] },
  { id: "SEM-D11", domain: "thorax", turns: ["Est-ce que le photon-counting détecte mieux les nodules pulmonaires que le CT conventionnel ?"], intent: "comparer la détection", routes: ["UNDERSTAND", "DESIGN_STUDY"], objects: [["MODALITY", "photon-counting CT"], ["COMPARATOR", "CT conventionnel"], ["SCIENTIFIC_OBJECT", "nodules pulmonaires"]], relations: [["photon-counting CT", "COMPARES_WITH", "CT conventionnel"]], ambiguities: ["critère de mieux"] },
  { id: "SEM-D12", domain: "abdomen", turns: ["quantifier la graisse hépatique en IRM avant et après intervention"], intent: "quantifier longitudinalement", routes: ["DESIGN_STUDY"], objects: [["SCIENTIFIC_OBJECT", "graisse hépatique"], ["MODALITY", "IRM"], ["TIMING", "avant intervention"], ["TIMING", "après intervention"]], relations: [["graisse hépatique", "MEASURED_BY", "IRM"]] },
  { id: "SEM-D13", domain: "musculosquelettique", turns: ["cartilage genou T2 mapping suivi 12 mois"], intent: "suivre", routes: ["DESIGN_STUDY", "FORMALIZE_IDEA"], objects: [["SCIENTIFIC_OBJECT", "cartilage du genou"], ["METHOD", "T2 mapping"], ["TIMING", "12 mois"]], relations: [["cartilage du genou", "MEASURED_BY", "T2 mapping"]] },
  { id: "SEM-D14", domain: "pédiatrie", turns: ["Perfusion cérébrale chez l'enfant par ASL, sans injection"], intent: "mesurer", routes: ["DESIGN_STUDY"], objects: [["SCIENTIFIC_OBJECT", "perfusion cérébrale"], ["POPULATION", "enfant"], ["METHOD", "ASL"], ["CONSTRAINT", "sans injection"]], relations: [["ASL", "MEASURES", "perfusion cérébrale"]] },
  { id: "SEM-D15", domain: "validation méthodologique", turns: ["Valider la répétabilité de l'ECV entre deux scanners"], intent: "valider la répétabilité", routes: ["DESIGN_STUDY"], objects: [["SCIENTIFIC_INTENT", "répétabilité"], ["BIOMARKER", "ECV"], ["COMPARATOR", "deux scanners"]], relations: [["ECV", "COMPARED_ACROSS", "deux scanners"]] },
  { id: "SEM-D16", domain: "Core Lab", turns: ["Je veux savoir si une lecture centrale réduit la variabilité interlecteur"], intent: "évaluer", routes: ["FORMALIZE_IDEA", "DESIGN_STUDY"], objects: [["INTERVENTION", "lecture centrale"], ["OUTCOME", "variabilité interlecteur"]], relations: [["lecture centrale", "AIMS_TO_MODIFY", "variabilité interlecteur"]], acceptable: ["hypothèse de réduction"], forbidden: ["réduction établie"] },
  { id: "SEM-D17", domain: "pronostic", turns: ["Le volume tumoral métabolique prédit-il la survie ?"], intent: "prédire", routes: ["FORMALIZE_IDEA"], objects: [["BIOMARKER", "volume tumoral métabolique"], ["OUTCOME", "survie"]], relations: [["volume tumoral métabolique", "PREDICTS_CANDIDATE", "survie"]], forbidden: ["causalité"] },
  { id: "SEM-D18", domain: "diagnostic", turns: ["TDM faible dose versus radio pour diagnostic pneumonie"], intent: "comparer diagnostic", routes: ["DESIGN_STUDY", "UNDERSTAND"], objects: [["MODALITY", "TDM faible dose"], ["COMPARATOR", "radiographie"], ["CONDITION", "pneumonie"]], relations: [["TDM faible dose", "COMPARES_WITH", "radiographie"]] },
  { id: "SEM-D19", domain: "interventionnel", turns: ["Ablation précoce ou tardive et remodelage atrial en IRM"], intent: "comparer", routes: ["FORMALIZE_IDEA", "DESIGN_STUDY"], objects: [["INTERVENTION", "ablation précoce"], ["COMPARATOR", "ablation tardive"], ["SCIENTIFIC_OBJECT", "remodelage atrial"], ["MODALITY", "IRM"]], relations: [["ablation précoce", "COMPARES_WITH", "ablation tardive"], ["remodelage atrial", "OBSERVED_BY", "IRM"]] },
  { id: "SEM-D20", domain: "observationnel", turns: ["association entre calcifications coronaires et événements à 3 ans"], intent: "étudier une association", routes: ["FORMALIZE_IDEA", "DESIGN_STUDY"], objects: [["BIOMARKER", "calcifications coronaires"], ["OUTCOME", "événements"], ["TIMING", "3 ans"]], relations: [["calcifications coronaires", "ASSOCIATED_WITH", "événements"]], forbidden: ["causalité"] },
  { id: "SEM-D21", domain: "multicentrique", turns: ["Harmoniser T1 mapping 1,5T et 3T dans 8 centres"], intent: "harmoniser", routes: ["DESIGN_STUDY"], objects: [["METHOD", "T1 mapping"], ["CONSTRAINT", "1,5T"], ["CONSTRAINT", "3T"], ["STUDY_DESIGN", "8 centres"]], relations: [["1,5T", "COMPARES_WITH", "3T"]] },
  { id: "SEM-D22", domain: "imagerie spectrale", turns: ["iode mesuré en dual energy vs photon counting"], intent: "comparer quantification", routes: ["UNDERSTAND", "DESIGN_STUDY"], objects: [["BIOMARKER", "iode"], ["METHOD", "dual energy"], ["METHOD", "photon counting"]], relations: [["dual energy", "COMPARES_WITH", "photon counting"]] },
  { id: "SEM-D23", domain: "neuro", turns: ["OEF et CMRO2 après AVC : évolution ?"], intent: "suivre", routes: ["FORMALIZE_IDEA", "DESIGN_STUDY"], objects: [["BIOMARKER", "OEF"], ["BIOMARKER", "CMRO2"], ["CONDITION", "AVC"], ["SCIENTIFIC_INTENT", "évolution"]], relations: [["OEF", "RELATED_TO", "CMRO2"]], ambiguities: ["temporalité"] },
  { id: "SEM-D24", domain: "oncologie", turns: ["radiomique CT pour réponse immunothérapie, prédiction baseline"], intent: "prédire", routes: ["FORMALIZE_IDEA", "DESIGN_STUDY"], objects: [["METHOD", "radiomique CT"], ["OUTCOME", "réponse à l'immunothérapie"], ["TIMING", "baseline"]], relations: [["radiomique CT", "PREDICTS_CANDIDATE", "réponse à l'immunothérapie"]] },
  { id: "SEM-D25", domain: "imagerie moléculaire", turns: ["Suivre deux traceurs PET dans le temps"], intent: "comparer longitudinalement", routes: ["DESIGN_STUDY"], objects: [["METHOD", "deux traceurs PET"], ["SCIENTIFIC_INTENT", "suivi longitudinal"]], ambiguities: ["identité des traceurs", "temporalité"] },
  { id: "SEM-D26", domain: "vascular", turns: ["plaque vulnérable : écho ou IRM ?"], intent: "comparer", routes: ["UNDERSTAND", "DESIGN_STUDY"], objects: [["SCIENTIFIC_OBJECT", "plaque vulnérable"], ["MODALITY", "échographie"], ["MODALITY", "IRM"]], relations: [["échographie", "COMPARES_WITH", "IRM"]], ambiguities: ["critère de comparaison"] },
  { id: "SEM-D27", domain: "méthodologie", turns: ["reproductibilité intersite segmentation foie IA"], intent: "évaluer la reproductibilité", routes: ["DESIGN_STUDY"], objects: [["SCIENTIFIC_INTENT", "reproductibilité intersite"], ["METHOD", "segmentation du foie par IA"]], forbidden: ["performance clinique"] },
  { id: "SEM-D28", domain: "thorax", turns: ["Dyspnée, CT inspiration expiration, air trapping quantifié"], intent: "quantifier", routes: ["DESIGN_STUDY", "FORMALIZE_IDEA"], objects: [["CONDITION", "dyspnée"], ["METHOD", "CT inspiration-expiration"], ["BIOMARKER", "air trapping"]], relations: [["air trapping", "MEASURED_BY", "CT inspiration-expiration"]] },
  { id: "SEM-D29", domain: "correction", turns: ["Je veux comparer le stenting immédiat et différé avec la taille d'infarctus comme critère principal en IRM.", "Non, ce n'est pas la taille de l'infarctus qui m'intéresse principalement, c'est la MVO."], intent: "comparer", routes: ["DESIGN_STUDY"], objects: [["INTERVENTION", "stenting immédiat"], ["COMPARATOR", "stenting différé"], ["ENDPOINT", "MVO"], ["MODALITY", "IRM"]], relations: [["stenting immédiat", "COMPARES_WITH", "stenting différé"]], correction: { rejectedMeaning: "taille d'infarctus", activeMeaning: "MVO" }, retain: ["stenting immédiat", "stenting différé", "IRM"] },
  { id: "SEM-D30", domain: "document", turns: ["Rédige le synopsis de mon étude"], intent: "document", routes: ["DOCUMENT"], objects: [["SCIENTIFIC_INTENT", "synopsis"]], ambiguities: ["Research Project absent ou insuffisant"], forbidden: ["synopsis généré"] },
]);

export const HOLDOUT_CASES: SemanticCompetenceCase[] = makeCases("HOLDOUT_CASES", [
  { id: "SEM-H01", domain: "néphrologie", turns: ["On voudrait opposer l'ADC cortical à la perfusion ASL pour caractériser le rein greffé."], intent: "comparer", routes: ["FORMALIZE_IDEA", "DESIGN_STUDY"], objects: [["BIOMARKER", "ADC cortical"], ["BIOMARKER", "perfusion ASL"], ["SCIENTIFIC_OBJECT", "rein greffé"]], relations: [["ADC cortical", "COMPARES_WITH", "perfusion ASL"]] },
  { id: "SEM-H02", domain: "gynécologie", turns: ["Endométriose profonde : est-ce que le T2* change après traitement, à six mois ?"], intent: "mesurer un changement", routes: ["DESIGN_STUDY", "FORMALIZE_IDEA"], objects: [["CONDITION", "endométriose profonde"], ["BIOMARKER", "T2*"], ["INTERVENTION", "traitement"], ["TIMING", "six mois"]], relations: [["T2*", "CHANGES_AFTER", "traitement"]] },
  { id: "SEM-H03", domain: "neurologie", turns: ["Chez SEP, le QSM serait lié au handicap mais je ne sais pas si je cherche une association ou du pronostic."], intent: "clarifier relation", routes: ["FORMALIZE_IDEA"], objects: [["CONDITION", "sclérose en plaques", ["SEP"]], ["BIOMARKER", "QSM"], ["OUTCOME", "handicap"]], relations: [["QSM", "RELATED_TO_CANDIDATE", "handicap"]], ambiguities: ["association ou pronostic"], forbidden: ["causalité"] },
  { id: "SEM-H04", domain: "oncologie", turns: ["Comparer DWI whole-body et PET PSMA pour repérer les métastases, pas pour mesurer la réponse."], intent: "comparer détection", routes: ["UNDERSTAND", "DESIGN_STUDY"], objects: [["METHOD", "DWI whole-body"], ["METHOD", "PET PSMA"], ["SCIENTIFIC_OBJECT", "métastases"], ["CONSTRAINT", "pas mesure de réponse"]], relations: [["DWI whole-body", "COMPARES_WITH", "PET PSMA"]], forbidden: ["réponse thérapeutique"] },
  { id: "SEM-H05", domain: "pédiatrie", turns: ["sans sédation, IRM poumon chez mucoviscidose, suivre ventilation"], intent: "suivre", routes: ["DESIGN_STUDY"], objects: [["CONSTRAINT", "sans sédation"], ["MODALITY", "IRM pulmonaire"], ["CONDITION", "mucoviscidose"], ["SCIENTIFIC_OBJECT", "ventilation"]], relations: [["ventilation", "OBSERVED_BY", "IRM pulmonaire"]] },
  { id: "SEM-H06", domain: "foie", turns: ["MRE ou élastographie US : laquelle est la plus reproductible pour fibrose hépatique multicentre ?"], intent: "comparer reproductibilité", routes: ["DESIGN_STUDY", "UNDERSTAND"], objects: [["METHOD", "MRE"], ["METHOD", "élastographie ultrasonore"], ["SCIENTIFIC_OBJECT", "fibrose hépatique"], ["STUDY_DESIGN", "multicentrique"]], relations: [["MRE", "COMPARES_WITH", "élastographie ultrasonore"]], ambiguities: ["définition de reproductibilité"] },
  { id: "SEM-H07", domain: "cardiaque", turns: ["post myocardite : mapping natif et strain, lequel annonce la récupération VG ?"], intent: "comparer pronostic", routes: ["FORMALIZE_IDEA", "DESIGN_STUDY"], objects: [["CONDITION", "post-myocardite"], ["METHOD", "mapping natif"], ["BIOMARKER", "strain"], ["OUTCOME", "récupération ventriculaire gauche"]], relations: [["mapping natif", "COMPARES_WITH", "strain"]] },
  { id: "SEM-H08", domain: "neurovasculaire", turns: ["Tmax 6 s n'est pas mon endpoint; je veux décrire le décalage bolus entre CT perfusion et ASL."], intent: "comparer mesure", routes: ["FORMALIZE_IDEA", "DESIGN_STUDY"], objects: [["CONSTRAINT", "Tmax 6 s exclu comme endpoint"], ["SCIENTIFIC_OBJECT", "décalage de bolus"], ["METHOD", "CT perfusion"], ["METHOD", "ASL"]], relations: [["CT perfusion", "COMPARES_WITH", "ASL"]], forbidden: ["Tmax 6 s adopté comme endpoint"] },
  { id: "SEM-H09", domain: "imagerie spectrale", turns: ["Le virtuel sans contraste peut-il remplacer le sans injection pour les calculs de calcium ?"], intent: "évaluer substitution", routes: ["UNDERSTAND", "DESIGN_STUDY"], objects: [["METHOD", "virtual non contrast"], ["COMPARATOR", "acquisition sans injection"], ["SCIENTIFIC_OBJECT", "calcium"]], relations: [["virtual non contrast", "COMPARES_WITH", "acquisition sans injection"]], forbidden: ["équivalence établie"] },
  { id: "SEM-H10", domain: "muscle", turns: ["Après exercice, phosphore 31P et BOLD musculaire; voir récupération énergétique."], intent: "suivre", routes: ["FORMALIZE_IDEA", "DESIGN_STUDY"], objects: [["TIMING", "après exercice"], ["METHOD", "spectroscopie 31P"], ["METHOD", "BOLD musculaire"], ["SCIENTIFIC_OBJECT", "récupération énergétique"]], relations: [["spectroscopie 31P", "RELATED_TO", "récupération énergétique"]] },
  { id: "SEM-H11", domain: "vasculaire", turns: ["On suit diamètre aortique, mais c'est la vitesse de croissance plutôt que le diamètre brut qui doit compter."], intent: "suivre", routes: ["DESIGN_STUDY"], objects: [["SCIENTIFIC_OBJECT", "diamètre aortique"], ["ENDPOINT", "vitesse de croissance"]], relations: [["vitesse de croissance", "DERIVES_FROM", "diamètre aortique"]], forbidden: ["diamètre brut adopté comme endpoint principal"] },
  { id: "SEM-H12", domain: "radiothérapie", turns: ["delta-radiomics avant et pendant RT pour toxicité pulmonaire tardive"], intent: "prédire", routes: ["DESIGN_STUDY", "FORMALIZE_IDEA"], objects: [["METHOD", "delta-radiomics"], ["TIMING", "avant radiothérapie"], ["TIMING", "pendant radiothérapie"], ["OUTCOME", "toxicité pulmonaire tardive"]], relations: [["delta-radiomics", "RELATED_TO_CANDIDATE", "toxicité pulmonaire tardive"]] },
  { id: "SEM-H13", domain: "imagerie interventionnelle", turns: ["embolisation maintenant ou en deux temps; volume perfusé en cone-beam CT"], intent: "comparer", routes: ["DESIGN_STUDY"], objects: [["INTERVENTION", "embolisation immédiate"], ["COMPARATOR", "embolisation en deux temps"], ["BIOMARKER", "volume perfusé"], ["MODALITY", "cone-beam CT"]], relations: [["embolisation immédiate", "COMPARES_WITH", "embolisation en deux temps"], ["volume perfusé", "MEASURED_BY", "cone-beam CT"]] },
  { id: "SEM-H14", domain: "Core Lab", turns: ["Double lecture aveugle, mais adjudication seulement si écart au-dessus d'un seuil encore indéfini."], intent: "concevoir lecture", routes: ["DESIGN_STUDY"], objects: [["METHOD", "double lecture aveugle"], ["METHOD", "adjudication conditionnelle"], ["UNKNOWN", "seuil d'écart indéfini"]], relations: [["adjudication conditionnelle", "TRIGGERED_BY", "seuil d'écart indéfini"]], ambiguities: ["seuil d'adjudication"] },
  { id: "SEM-H15", domain: "données", turns: ["Cohorte rétrospective, trois hôpitaux, DICOM incomplets : estimer le taux de non-évaluables."], intent: "quantifier faisabilité", routes: ["DESIGN_STUDY"], objects: [["STUDY_DESIGN", "cohorte rétrospective"], ["STUDY_DESIGN", "trois hôpitaux"], ["CONSTRAINT", "DICOM incomplets"], ["OUTCOME", "taux de non-évaluables"]], relations: [["DICOM incomplets", "INFLUENCES", "taux de non-évaluables"]] },
  { id: "SEM-H16", domain: "diagnostic", turns: ["Évaluer une séquence ultracourte pour voir le cortex osseux; le comparateur n'est pas encore choisi."], intent: "évaluer", routes: ["FORMALIZE_IDEA", "DESIGN_STUDY"], objects: [["METHOD", "séquence ultracourte"], ["SCIENTIFIC_OBJECT", "cortex osseux"], ["UNKNOWN", "comparateur non choisi"]], relations: [["séquence ultracourte", "OBSERVES", "cortex osseux"]], ambiguities: ["comparateur"] },
  { id: "SEM-H17", domain: "cardiologie", turns: ["Faut-il regarder l'œdème ou la MVO pour expliquer le no-reflow, sans dire que l'un cause l'autre ?"], intent: "comparer explication", routes: ["UNDERSTAND", "FORMALIZE_IDEA"], objects: [["PHENOMENON", "œdème"], ["PHENOMENON", "MVO"], ["SCIENTIFIC_OBJECT", "no-reflow"], ["CONSTRAINT", "ne pas affirmer de causalité"]], relations: [["œdème", "COMPARES_WITH", "MVO"]], forbidden: ["causalité"] },
  { id: "SEM-H18", domain: "thorax", turns: ["fibrose pulmonaire quantitative : progression à 1 an avec CT, mortalité pas concernée"], intent: "suivre progression", routes: ["DESIGN_STUDY"], objects: [["SCIENTIFIC_OBJECT", "fibrose pulmonaire quantitative"], ["TIMING", "1 an"], ["MODALITY", "CT"], ["CONSTRAINT", "mortalité exclue"]], relations: [["fibrose pulmonaire quantitative", "MEASURED_BY", "CT"]], forbidden: ["mortalité comme outcome"] },
  { id: "SEM-H19", domain: "prostate", turns: ["PI-RADS ou radiomique pour prédire upgrading, biopsie comme référence"], intent: "comparer prédiction", routes: ["DESIGN_STUDY", "FORMALIZE_IDEA"], objects: [["BIOMARKER", "PI-RADS"], ["METHOD", "radiomique"], ["OUTCOME", "upgrading"], ["METHOD", "biopsie de référence"]], relations: [["PI-RADS", "COMPARES_WITH", "radiomique"]] },
  { id: "SEM-H20", domain: "foie", turns: ["ASL hépatique sans gadolinium chez insuffisants rénaux, faisable ?"], intent: "évaluer faisabilité", routes: ["UNDERSTAND", "DESIGN_STUDY"], objects: [["METHOD", "ASL hépatique"], ["CONSTRAINT", "sans gadolinium"], ["POPULATION", "insuffisance rénale"]], forbidden: ["faisabilité confirmée"] },
  { id: "SEM-H21", domain: "multimodal", turns: ["Fusionner échographie de contraste et CT, non pour les comparer mais pour localiser la même lésion."], intent: "recalage multimodal", routes: ["DESIGN_STUDY"], objects: [["MODALITY", "échographie de contraste"], ["MODALITY", "CT"], ["SCIENTIFIC_OBJECT", "même lésion"], ["CONSTRAINT", "pas une comparaison"]], relations: [["échographie de contraste", "CO_LOCALIZES_WITH", "CT"]] },
  { id: "SEM-H22", domain: "neuro-oncologie", turns: ["pseudoprogression vs récidive: perfusion DSC + spectro, résultat histologique pas toujours dispo"], intent: "distinguer", routes: ["DESIGN_STUDY", "FORMALIZE_IDEA"], objects: [["CONDITION", "pseudoprogression"], ["CONDITION", "récidive"], ["METHOD", "perfusion DSC"], ["METHOD", "spectroscopie"], ["CONSTRAINT", "histologie pas toujours disponible"]], relations: [["pseudoprogression", "COMPARES_WITH", "récidive"]] },
  { id: "SEM-H23", domain: "méthodologie", turns: ["Test-retest ADC tumeur, même jour, sans traitement entre les deux"], intent: "évaluer répétabilité", routes: ["DESIGN_STUDY"], objects: [["BIOMARKER", "ADC tumoral"], ["STUDY_DESIGN", "test-retest"], ["TIMING", "même jour"], ["CONSTRAINT", "sans traitement entre mesures"]], relations: [["ADC tumoral", "REPEATED_AT", "même jour"]] },
  { id: "SEM-H24", domain: "grossesse", turns: ["Placenta IVIM et T2*, relation avec croissance fœtale, mais aucune injection."], intent: "étudier relation", routes: ["FORMALIZE_IDEA", "DESIGN_STUDY"], objects: [["SCIENTIFIC_OBJECT", "placenta"], ["METHOD", "IVIM"], ["BIOMARKER", "T2*"], ["OUTCOME", "croissance fœtale"], ["CONSTRAINT", "aucune injection"]], relations: [["T2*", "RELATED_TO_CANDIDATE", "croissance fœtale"]] },
  { id: "SEM-H25", domain: "K-edge", turns: ["Deux agents K-edge injectés pour séparer inflammation et vascularisation : projet exploratoire."], intent: "imagerie multi-contraste", routes: ["FORMALIZE_IDEA", "DESIGN_STUDY"], objects: [["INTERVENTION", "deux agents K-edge"], ["PHENOMENON", "inflammation"], ["PHENOMENON", "vascularisation"], ["STUDY_DESIGN", "exploratoire"]], relations: [["inflammation", "DISTINGUISHED_FROM", "vascularisation"]], forbidden: ["agent approuvé", "dose"] },
  { id: "SEM-H26", domain: "oral", turns: ["Moi ce qui m'intéresse c'est pas la perfusion, c'est combien de temps l'oxygénation met à revenir après l'effort."], intent: "mesurer récupération", routes: ["FORMALIZE_IDEA", "DESIGN_STUDY"], objects: [["CONSTRAINT", "perfusion exclue"], ["SCIENTIFIC_OBJECT", "oxygénation"], ["OUTCOME", "temps de récupération"], ["TIMING", "après effort"]], relations: [["oxygénation", "RECOVERS_AFTER", "effort"]], forbidden: ["perfusion comme endpoint"] },
  { id: "SEM-H27", domain: "négatif", turns: ["Ne pas comparer les constructeurs. Je veux uniquement voir si le changement de logiciel modifie le T1."], intent: "évaluer effet technique", routes: ["DESIGN_STUDY"], objects: [["CONSTRAINT", "constructeurs non comparés"], ["INTERVENTION", "changement de logiciel"], ["BIOMARKER", "T1"]], relations: [["changement de logiciel", "MAY_MODIFY", "T1"]], forbidden: ["comparaison de constructeurs"] },
  { id: "SEM-H28", domain: "objectifs multiples", turns: ["Mesurer perfusion rénale et prédire déclin du DFG; ASL maintenant, suivi deux ans."], intent: "mesurer et prédire", routes: ["DESIGN_STUDY"], objects: [["SCIENTIFIC_OBJECT", "perfusion rénale"], ["OUTCOME", "déclin du DFG"], ["METHOD", "ASL"], ["TIMING", "deux ans"]], relations: [["ASL", "MEASURES", "perfusion rénale"], ["perfusion rénale", "PREDICTS_CANDIDATE", "déclin du DFG"]] },
  { id: "SEM-H29", domain: "correction multi-tour", turns: ["Comparer PET et IRM pour la réponse tumorale à trois mois.", "En fait gardez l'IRM, mais le PET n'est plus dans le projet; ajoutez le CT spectral."], intent: "comparer modalités", routes: ["DESIGN_STUDY"], objects: [["MODALITY", "IRM"], ["MODALITY", "CT spectral"], ["OUTCOME", "réponse tumorale"], ["TIMING", "trois mois"]], relations: [["IRM", "COMPARES_WITH", "CT spectral"]], correction: { rejectedMeaning: "PET", activeMeaning: "CT spectral" }, retain: ["IRM", "réponse tumorale", "trois mois"] },
  { id: "SEM-H30", domain: "sans imagerie", turns: ["Comparer deux parcours de consentement et mesurer le taux de refus dans quatre centres."], intent: "comparer", routes: ["DESIGN_STUDY"], objects: [["INTERVENTION", "deux parcours de consentement"], ["OUTCOME", "taux de refus"], ["STUDY_DESIGN", "quatre centres"]], forbidden: ["modalité d'imagerie"] },
]);

export const SEMANTIC_COMPETENCE_CASES = [...DEVELOPMENT_CASES, ...HOLDOUT_CASES];
