import type { DocumentProjection } from "./types";

const escapeHtml = (value: string) => value.replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;", "'": "&#39;" })[character] ?? character);
const list = (values: ReadonlyArray<string>) => `<ul>${values.map((item) => `<li>${escapeHtml(item)}</li>`).join("")}</ul>`;

export const renderProjectionHtml = (projection: Readonly<DocumentProjection>) => `<!doctype html>
<html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>${escapeHtml(projection.title)}</title></head>
<body><main><article data-projection-id="${escapeHtml(projection.projectionId)}">
<header><h1>${escapeHtml(projection.title)}</h1><dl><dt>Projection</dt><dd>${projection.projectionType} v${escapeHtml(projection.projectionVersion)}</dd><dt>État</dt><dd>${projection.lifecycle}</dd><dt>Readiness</dt><dd>${projection.readiness}</dd><dt>Projet source</dt><dd>${escapeHtml(projection.source.projectId)} · ${escapeHtml(projection.source.projectVersion)}</dd><dt>Template</dt><dd>${projection.source.template ? `${escapeHtml(projection.source.template.templateId)} · instance ${escapeHtml(projection.source.template.templateInstanceId)}` : "LEGACY_DIRECT_PROJECT_PROJECTION"}</dd><dt>Profil</dt><dd>${escapeHtml(projection.profile)}</dd><dt>Usage</dt><dd>${escapeHtml(projection.usage)}</dd><dt>Audience</dt><dd>${escapeHtml(projection.audience)}</dd></dl><p><strong>Frontière :</strong> projection en lecture seule ; ni vérité du projet, ni protocole clinique exécutable, ni approbation.</p></header>
${projection.sections.map((section) => `<section id="${escapeHtml(section.sectionId)}"><h2>${section.order}. ${escapeHtml(section.title)}</h2><p><strong>Statut :</strong> ${section.status} · <strong>Applicabilité :</strong> ${section.applicability} · <strong>TMP :</strong> ${section.templateStatus ?? "LEGACY"}</p>${section.templateNodeIds.length ? `<h3>Nœuds TMP</h3>${list(section.templateNodeIds)}` : ""}${section.futureReason ? `<p><strong>Dépendance future :</strong> ${escapeHtml(section.futureReason)}</p>` : ""}${section.statusReasons.length ? `<h3>Règles de décision</h3>${list(section.statusReasons)}` : ""}${section.blocks.map((block) => `<div data-commitment="${block.commitment}"><h3>${escapeHtml(block.label ?? block.kind)}</h3>${list(block.items)}</div>`).join("")}${section.unknowns.length ? `<h3>Inconnues</h3>${list(section.unknowns)}` : ""}${section.limitations.length ? `<h3>Limitations</h3>${list(section.limitations)}` : ""}${section.contradictions.length ? `<h3>Contradictions</h3>${list(section.contradictions)}` : ""}${section.requirementIds.length ? `<h3>Exigences REG-001</h3>${list(section.requirementIds)}` : ""}${section.patternIds.length ? `<h3>Patterns DOC-002</h3>${list(section.patternIds)}` : ""}${section.humanDecisionIds.length ? `<h3>Décisions humaines liées</h3>${list(section.humanDecisionIds)}` : ""}<h3>Provenance</h3>${list(section.provenanceRefs)}</section>`).join("\n")}
<section><h2>Registre des décisions humaines</h2>${projection.humanDecisions.length ? list(projection.humanDecisions.map((item) => `${item.status} — ${item.gateId} — ${item.actor ?? "acteur non attribué"} — mandat ${item.mandate ?? "non attribué"} — version ${item.version} — ${item.reason ?? "raison non renseignée"}`)) : "<p>Aucune décision transportée.</p>"}</section>
<footer><p>Digest de projection : ${escapeHtml(projection.projectionDigest)}</p></footer></article></main></body></html>`;
