const freeze = (value) => Object.freeze(value);

export const territoryRoadmap = freeze({
  roadmapId: "noxia:scientific-territory:roadmap:1.0.0",
  responsibility: "PRIORITIZE_TERRITORY_FAMILIES_WITHOUT_SELECTING_CAMPAIGNS",
  selectionAuthority: "SCIENTIFIC_KNOWLEDGE_CATALOG_CAMPAIGN_PLANNER",
  manualCampaignSelectionAllowed: false,
  waves: freeze([
    freeze({
      waveId: "TERRITORY-WAVE-FOUNDATIONS",
      priority: "FOUNDATION",
      objective: "Établir les concepts transverses dont dépendent les comparaisons et les mesures de plusieurs spécialités.",
      territoryIds: freeze(["modalities-acquisition", "measurements-biomarkers", "physics-instrumentation", "quality-safety", "informatics-workflows"]),
      naturalClusters: freeze(["modalités et acquisition", "métrologie et qualité", "standards et interopérabilité", "terminologie et définitions", "protocoles documentaires"]),
      dependsOnWaveIds: freeze([]),
      catalogRule: "Select HIGH priority nodes inside these territories only when the catalogue records an actionable source, assertion, provenance or synthesis gap.",
    }),
    freeze({
      waveId: "TERRITORY-WAVE-CLINICAL-CORE",
      priority: "PRIMARY",
      objective: "Couvrir les grandes spécialités anatomiques et les questions cliniques transverses à forte valeur documentaire.",
      territoryIds: freeze(["anatomy-specialties", "clinical-applications"]),
      naturalClusters: freeze(["neurovasculaire", "cardiaque et vasculaire", "thorax", "abdomen et foie", "oncologie", "musculosquelettique", "pédiatrie et urgence"]),
      dependsOnWaveIds: freeze(["TERRITORY-WAVE-FOUNDATIONS"]),
      catalogRule: "The catalogue resolves actual order from coverage, dependencies and priority; the territory supplies no hand-picked node.",
    }),
    freeze({
      waveId: "TERRITORY-WAVE-QUANTITATIVE",
      priority: "PRIMARY",
      objective: "Étendre les biomarqueurs, mesures et comparaisons quantitatives au-delà des pilotes existants.",
      territoryIds: freeze(["measurements-biomarkers", "research-evidence"]),
      naturalClusters: freeze(["diffusion", "perfusion", "relaxométrie", "oxygénation et métabolisme", "mécanique", "phénotypage", "qualification de biomarqueurs"]),
      dependsOnWaveIds: freeze(["TERRITORY-WAVE-FOUNDATIONS"]),
      catalogRule: "Measurement campaigns require explicit method, unit, applicability and provenance gaps in the catalogue.",
    }),
    freeze({
      waveId: "TERRITORY-WAVE-COMPUTATIONAL",
      priority: "PRIMARY",
      objective: "Couvrir traitement d'image, radiomique et IA selon des contrats de validation indépendants des applications cliniques.",
      territoryIds: freeze(["computational-imaging", "quality-safety", "informatics-workflows"]),
      naturalClusters: freeze(["recalage", "segmentation", "radiomique", "validation IA", "incertitude", "visualisation", "interopérabilité IA"]),
      dependsOnWaveIds: freeze(["TERRITORY-WAVE-FOUNDATIONS"]),
      catalogRule: "No internal dataset, training job or deployed model may be created by a scientific enrichment campaign.",
    }),
    freeze({
      waveId: "TERRITORY-WAVE-INTERVENTIONAL",
      priority: "SECONDARY",
      objective: "Documenter guidage, techniques et résultats d'intervention sans créer de workflow exécutable ni de recommandation clinique automatique.",
      territoryIds: freeze(["interventional-imaging", "quality-safety", "clinical-applications"]),
      naturalClusters: freeze(["vasculaire", "neurointervention", "oncologie interventionnelle", "biopsie et drainage", "fusion et navigation", "sécurité procédurale"]),
      dependsOnWaveIds: freeze(["TERRITORY-WAVE-FOUNDATIONS", "TERRITORY-WAVE-CLINICAL-CORE"]),
      catalogRule: "Only documentary scientific objects are eligible; operational procedure configuration remains out of scope.",
    }),
    freeze({
      waveId: "TERRITORY-WAVE-FUTURE",
      priority: "FUTURE",
      objective: "Réévaluer périodiquement les technologies émergentes et les zones adjacentes conditionnelles.",
      territoryIds: freeze(["modalities-acquisition", "physics-instrumentation", "computational-imaging", "research-evidence"]),
      naturalClusters: freeze(["modalités émergentes", "nouveaux détecteurs", "bas et ultra-haut champ", "modèles fondamentaux", "prospective"]),
      dependsOnWaveIds: freeze(["TERRITORY-WAVE-FOUNDATIONS"]),
      catalogRule: "Future nodes require an explicit territory revision before the catalogue can schedule them.",
    }),
  ]),
  governance: freeze({
    territoryRevisionRequiredForNewDomain: true,
    catalogueCoverageCannotExpandTerritory: true,
    campaignsCannotCreateTerritoryNodes: true,
    projectedNodesMayReenterWithinTerritory: true,
    publicProjectionRequiresSeparateReadiness: true,
  }),
});
