import { validationDigest } from "./canonical";
import { VAL001_CHECKPOINT_IDS, VALIDATION_INVARIANT_REFERENCE_REGISTRY } from "./invariant-registry";
import type { CheckpointApplicability, ValidationArtifactReference, ValidationCheckpointDefinition, ValidationCheckpointRegistry, ValidationProductGateReference } from "./product-contracts";

const CP = VAL001_CHECKPOINT_IDS;
const invariantsFor = (checkpointId: string) => VALIDATION_INVARIANT_REFERENCE_REGISTRY.invariants.filter((item) => item.applicableCheckpoints.includes(checkpointId)).map((item) => item.invariantId);

const definition = (input: Omit<ValidationCheckpointDefinition, "version" | "invariantRefs" | "semanticReviewPolicy" | "humanReviewPolicy" | "severityPolicy" | "defaultDispositionPolicy" | "implementationStatus"> & Partial<Pick<ValidationCheckpointDefinition, "semanticReviewPolicy" | "humanReviewPolicy" | "implementationStatus">>): ValidationCheckpointDefinition => ({
  ...input,
  version: "1.0.0",
  invariantRefs: invariantsFor(input.checkpointId),
  semanticReviewPolicy: input.semanticReviewPolicy ?? "DISABLED_BY_DEFAULT",
  humanReviewPolicy: input.humanReviewPolicy ?? "PREPARE_REQUEST_ONLY",
  severityPolicy: "DOMAIN_INVARIANT_POLICY",
  defaultDispositionPolicy: "DOMAIN_POLICY_THEN_CHECKPOINT_POLICY",
  implementationStatus: input.implementationStatus ?? "CONTRACT_READY",
});

const CHECKPOINTS: ValidationCheckpointDefinition[] = [
  definition({ checkpointId: CP.requestInterpretation, name: "Request to Scientific Interpretation", description: "Observes preservation of the visible request in the runtime-neutral Contribution.", sourceArtifactTypes: ["ORIGINAL_REQUEST"], targetArtifactTypes: ["SCIENTIFIC_INTERPRETATION_CONTRIBUTION"], sourceOwner: "USER", targetOwner: "SCIENTIFIC_INTERPRETATION", validationPlanes: ["STRUCTURAL", "PROVENANCE_LINEAGE", "EPISTEMIC", "SEMANTIC_FIDELITY", "REPRODUCIBILITY"], productGateRefs: ["CONTRIBUTION_ADOPTION", "CANDIDATE_PREVIEW"], applicableWhen: ["Visible request and Contribution are available."], notApplicableWhen: [], limitations: ["Audit-D findings are referenced; Audit-D is never recomputed by VAL."], historicalCheckpointRefs: [] }),
  definition({ checkpointId: CP.interpretationThinking, name: "Scientific Interpretation to Scientific Thinking", description: "Observes the nominal Contribution handoff to Scientific Thinking.", sourceArtifactTypes: ["SCIENTIFIC_INTERPRETATION_CONTRIBUTION"], targetArtifactTypes: ["SCIENTIFIC_THINKING_RESULT"], sourceOwner: "SCIENTIFIC_INTERPRETATION", targetOwner: "ST-001", validationPlanes: ["STRUCTURAL", "PROVENANCE_LINEAGE", "OWNERSHIP", "EPISTEMIC", "SEMANTIC_FIDELITY", "DECISION"], productGateRefs: ["PROJECT_FREEZE", "CANDIDATE_PREVIEW"], applicableWhen: ["Nominal runtime-neutral Contribution and ST result are available."], notApplicableWhen: ["Legacy SEMANTIC_MODEL is the only source."], limitations: ["This identity supersedes, rather than silently redefines, VAL-SEM-ST-001."], historicalCheckpointRefs: [{ checkpointId: "VAL-SEM-ST-001", version: "1.0.0", mapping: "SUPERSEDED" }] }),
  definition({ checkpointId: CP.thinkingObservationImaging, name: "Scientific Thinking to OBS or Imaging", description: "Observes available OBS handoffs or Imaging contributions without creating an OBS runtime.", sourceArtifactTypes: ["SCIENTIFIC_THINKING_RESULT"], targetArtifactTypes: ["OBSERVATION_HANDOFF", "IMAGING_CONTRIBUTION"], sourceOwner: "ST-001", targetOwner: "OBS-001_OR_IMG-001", validationPlanes: ["STRUCTURAL", "PROVENANCE_LINEAGE", "OWNERSHIP", "EPISTEMIC", "SEMANTIC_FIDELITY", "READINESS"], productGateRefs: ["PROJECT_FREEZE", "CANDIDATE_PREVIEW"], applicableWhen: ["An OBS handoff or Imaging contribution exists."], notApplicableWhen: ["The Project explicitly records Imaging/OBS as NOT_APPLICABLE."], limitations: ["No autonomous OBS V2 runtime is required or simulated."], historicalCheckpointRefs: [{ checkpointId: "VAL-ST-IMG-001", version: "1.0.0", mapping: "PARTIAL" }] }),
  definition({ checkpointId: CP.scientificStateProject, name: "Scientific State to Research Project", description: "Observes adopted scientific state entering the versioned Research Project.", sourceArtifactTypes: ["SCIENTIFIC_THINKING_RESULT", "OBSERVATION_HANDOFF", "IMAGING_CONTRIBUTION", "SCIENTIFIC_INTERPRETATION_CONTRIBUTION"], targetArtifactTypes: ["RESEARCH_PROJECT"], sourceOwner: "SCIENTIFIC_DOMAIN_OWNERS", targetOwner: "RESEARCH_PROJECT", validationPlanes: ["STRUCTURAL", "IDENTITY_VERSION", "PROVENANCE_LINEAGE", "OWNERSHIP", "EPISTEMIC", "SEMANTIC_FIDELITY", "DECISION", "READINESS"], productGateRefs: ["CONTRIBUTION_ADOPTION", "PROJECT_FREEZE", "CANDIDATE_PREVIEW"], applicableWhen: ["At least one scientific handoff and a Project artifact are available."], notApplicableWhen: [], limitations: ["Only Human Decision can adopt a contribution."], historicalCheckpointRefs: [{ checkpointId: "VAL-IMG-PRJ-001", version: "1.0.0", mapping: "PARTIAL" }] }),
  definition({ checkpointId: CP.projectStudyData, name: "Research Project to Study Data Plan", description: "Observes canonical data needs and expected occasions at design time.", sourceArtifactTypes: ["RESEARCH_PROJECT"], targetArtifactTypes: ["STUDY_DATA_PLAN_CONTRIBUTION"], sourceOwner: "RESEARCH_PROJECT", targetOwner: "CDM-001_DESIGN_TIME_PLANNING", validationPlanes: ["STRUCTURAL", "IDENTITY_VERSION", "PROVENANCE_LINEAGE", "OWNERSHIP", "EPISTEMIC", "DECISION", "READINESS", "REPRODUCIBILITY"], productGateRefs: ["CONTRIBUTION_ADOPTION", "DMP_GENERATION", "SAP_GENERATION", "V1_READY", "CANDIDATE_PREVIEW"], applicableWhen: ["A Project and Study Data planning contribution exist."], notApplicableWhen: ["Study Data is explicitly NOT_APPLICABLE."], limitations: ["VariableOccurrence and realized values are outside V1."], historicalCheckpointRefs: [] }),
  definition({ checkpointId: CP.studyDataDataManagement, name: "Study Data Plan to Data Management Plan", description: "Observes design-time collection and Data Management planning.", sourceArtifactTypes: ["STUDY_DATA_PLAN_CONTRIBUTION"], targetArtifactTypes: ["DATA_MANAGEMENT_PLANNING_CONTRIBUTION"], sourceOwner: "CDM-001_DESIGN_TIME_PLANNING", targetOwner: "DM-001_DESIGN_TIME_PLANNING", validationPlanes: ["STRUCTURAL", "IDENTITY_VERSION", "PROVENANCE_LINEAGE", "OWNERSHIP", "EPISTEMIC", "SEMANTIC_FIDELITY", "PROJECTION", "READINESS"], productGateRefs: ["DMP_GENERATION", "SAP_GENERATION", "V1_READY"], applicableWhen: ["Study Data and Data Management planning contributions exist."], notApplicableWhen: ["Data Management is explicitly NOT_APPLICABLE."], limitations: ["Queries, corrections, locks and releases remain DEFERRED_TO_REALIZED_TIME."], historicalCheckpointRefs: [] }),
  definition({ checkpointId: CP.scientificStateBiostatistics, name: "Scientific and Data State to Biostatistics Plan", description: "Observes design-time analysis specifications without choosing a method or sample size.", sourceArtifactTypes: ["RESEARCH_PROJECT", "OBSERVATION_HANDOFF", "STUDY_DATA_PLAN_CONTRIBUTION", "DATA_MANAGEMENT_PLANNING_CONTRIBUTION"], targetArtifactTypes: ["BIOSTATISTICS_PLANNING_CONTRIBUTION"], sourceOwner: "PROJECT_OBS_CDM_DM", targetOwner: "BIOSTATISTICS-001_DESIGN_TIME_PLANNING", validationPlanes: ["STRUCTURAL", "IDENTITY_VERSION", "PROVENANCE_LINEAGE", "OWNERSHIP", "EPISTEMIC", "SEMANTIC_FIDELITY", "DECISION", "PROJECTION", "READINESS"], productGateRefs: ["CONTRIBUTION_ADOPTION", "SAP_GENERATION", "V1_READY", "CANDIDATE_PREVIEW"], applicableWhen: ["Required design-time sources and Biostatistics planning contribution exist."], notApplicableWhen: ["Biostatistics is explicitly NOT_APPLICABLE."], limitations: ["AnalysisDataset, AnalysisExecution and AnalysisResult are outside V1."], historicalCheckpointRefs: [] }),
  definition({ checkpointId: CP.dataAnalysisTemplate, name: "Project Data and Analysis to Template", description: "Observes structural composition of Project, Data and Analysis sources into TMP.", sourceArtifactTypes: ["RESEARCH_PROJECT", "PROJECT_DATA_ANALYSIS_VIEW", "STUDY_DATA_PLAN_CONTRIBUTION", "DATA_MANAGEMENT_PLANNING_CONTRIBUTION", "BIOSTATISTICS_PLANNING_CONTRIBUTION"], targetArtifactTypes: ["TEMPLATE_INSTANCE"], sourceOwner: "PROJECT_AND_DOMAIN_OWNERS", targetOwner: "TMP-001", validationPlanes: ["STRUCTURAL", "IDENTITY_VERSION", "PROVENANCE_LINEAGE", "OWNERSHIP", "EPISTEMIC", "PROJECTION", "READINESS"], productGateRefs: ["PROTOCOL_GENERATION", "DMP_GENERATION", "SAP_GENERATION", "V1_READY"], applicableWhen: ["A Template instance and at least one governed source exist."], notApplicableWhen: [], limitations: ["TMP composes structure and never decides scientific content."], historicalCheckpointRefs: [{ checkpointId: "VAL-TMP-001", version: "1.0.0", mapping: "PARTIAL" }] }),
  definition({ checkpointId: CP.templateDocument, name: "Template to Document Projection", description: "Observes a projection whose structure comes from TMP and content from source owners.", sourceArtifactTypes: ["TEMPLATE_INSTANCE"], targetArtifactTypes: ["DOCUMENT_PROJECTION"], sourceOwner: "TMP-001_AND_RESEARCH_PROJECT", targetOwner: "DOC-001", validationPlanes: ["STRUCTURAL", "IDENTITY_VERSION", "PROVENANCE_LINEAGE", "OWNERSHIP", "EPISTEMIC", "PROJECTION", "READINESS", "REPRODUCIBILITY"], productGateRefs: ["PROTOCOL_GENERATION", "DMP_GENERATION", "SAP_GENERATION", "V1_READY"], applicableWhen: ["Template and Document projection exist."], notApplicableWhen: ["The projection is explicitly NOT_APPLICABLE."], limitations: ["Document validity is projection fidelity, not scientific qualification."], historicalCheckpointRefs: [{ checkpointId: "VAL-DOC-001", version: "1.0.0", mapping: "PARTIAL" }] }),
  definition({ checkpointId: CP.projectProductView, name: "Research Project to Product View", description: "Observes that workspace views remain read-only projections of Project state.", sourceArtifactTypes: ["RESEARCH_PROJECT"], targetArtifactTypes: ["PROJECT_DATA_ANALYSIS_VIEW"], sourceOwner: "RESEARCH_PROJECT", targetOwner: "PRODUCT_VIEW", validationPlanes: ["STRUCTURAL", "IDENTITY_VERSION", "PROVENANCE_LINEAGE", "OWNERSHIP", "EPISTEMIC", "DECISION", "PROJECTION", "READINESS"], productGateRefs: ["CANDIDATE_PREVIEW", "PROJECT_FREEZE", "V1_READY"], applicableWhen: ["Project and Product View are available."], notApplicableWhen: [], limitations: ["Part 2 declares gates only; no UI blocking is active."], historicalCheckpointRefs: [] }),
];

export const VALIDATION_CHECKPOINT_REGISTRY_V1: ValidationCheckpointRegistry = Object.freeze({
  registryId: "VAL-001-CHECKPOINT-REGISTRY",
  version: "1.0.0",
  checkpoints: CHECKPOINTS.map((item) => Object.freeze({ ...item })),
  digest: validationDigest(CHECKPOINTS),
  boundary: "DECLARATIVE_CHECKPOINTS_ONLY_NO_VALIDATION_EXECUTION",
});

export const VALIDATION_PRODUCT_GATES: readonly ValidationProductGateReference[] = Object.freeze([
  { gateId: "CONTRIBUTION_ADOPTION", owner: "RESEARCH_PROJECT", blockingSeverities: ["BLOCKING"], requiredCheckpoints: [CP.requestInterpretation, CP.scientificStateProject, CP.projectStudyData, CP.scientificStateBiostatistics], unresolvedFindingPolicy: "REQUIRE_REVIEW", limitations: ["Declared only; no Part 2 product enforcement."], activeInProduct: false },
  { gateId: "PROJECT_FREEZE", owner: "RESEARCH_PROJECT", blockingSeverities: ["BLOCKING"], requiredCheckpoints: [CP.interpretationThinking, CP.thinkingObservationImaging, CP.scientificStateProject, CP.projectProductView], unresolvedFindingPolicy: "BLOCK_ON_BLOCKING", limitations: ["Domain freeze guards remain authoritative."], activeInProduct: false },
  { gateId: "PROTOCOL_GENERATION", owner: "DOC-001", blockingSeverities: ["BLOCKING", "ERROR"], requiredCheckpoints: [CP.dataAnalysisTemplate, CP.templateDocument], unresolvedFindingPolicy: "BLOCK_ON_BLOCKING", limitations: ["Projection readiness only."], activeInProduct: false },
  { gateId: "DMP_GENERATION", owner: "DOC-001", blockingSeverities: ["BLOCKING", "ERROR"], requiredCheckpoints: [CP.projectStudyData, CP.studyDataDataManagement, CP.dataAnalysisTemplate, CP.templateDocument], unresolvedFindingPolicy: "BLOCK_ON_BLOCKING", limitations: ["Logical DMP projection only."], activeInProduct: false },
  { gateId: "SAP_GENERATION", owner: "DOC-001", blockingSeverities: ["BLOCKING", "ERROR"], requiredCheckpoints: [CP.projectStudyData, CP.studyDataDataManagement, CP.scientificStateBiostatistics, CP.dataAnalysisTemplate, CP.templateDocument], unresolvedFindingPolicy: "BLOCK_ON_BLOCKING", limitations: ["Logical SAP projection only."], activeInProduct: false },
  { gateId: "V1_READY", owner: "NOXIA_PRODUCT", blockingSeverities: ["BLOCKING", "ERROR"], requiredCheckpoints: Object.values(CP), unresolvedFindingPolicy: "REQUIRE_REVIEW", limitations: ["Never implies PD-011 qualification."], activeInProduct: false },
  { gateId: "CANDIDATE_PREVIEW", owner: "PRODUCT_VIEW", blockingSeverities: ["BLOCKING"], requiredCheckpoints: [CP.requestInterpretation, CP.projectProductView], unresolvedFindingPolicy: "ALLOW_WITH_VISIBLE_FINDINGS", limitations: ["Preview can remain available with visible non-blocking findings."], activeInProduct: false },
]);

export const listValidationCheckpointsV1 = () => structuredClone(VALIDATION_CHECKPOINT_REGISTRY_V1.checkpoints);
export const getValidationCheckpointV1 = (checkpointId: string, version?: string) => VALIDATION_CHECKPOINT_REGISTRY_V1.checkpoints.find((item) => item.checkpointId === checkpointId && (!version || item.version === version)) ?? null;
export const getValidationProductGate = (gateId: string) => VALIDATION_PRODUCT_GATES.find((item) => item.gateId === gateId) ?? null;

export const inspectCheckpointApplicability = (
  checkpoint: Readonly<ValidationCheckpointDefinition>,
  input: {
    sourceArtifact?: Readonly<ValidationArtifactReference> | null;
    targetArtifact?: Readonly<ValidationArtifactReference> | null;
    notApplicable?: boolean;
    realizedTimeRequired?: boolean;
    notReady?: boolean;
    decisionsRequired?: string[];
    limitations?: string[];
  },
): CheckpointApplicability => {
  const base = { checkpointId: checkpoint.checkpointId, checkpointVersion: checkpoint.version, decisionsRequired: [...(input.decisionsRequired ?? [])], limitations: [...checkpoint.limitations, ...(input.limitations ?? [])] };
  if (!input.sourceArtifact) return { ...base, status: "MISSING_SOURCE", reason: "Required source artifact is absent.", missingArtifacts: [...checkpoint.sourceArtifactTypes] };
  if (!input.targetArtifact) return { ...base, status: "MISSING_TARGET", reason: "Required target artifact is absent.", missingArtifacts: [...checkpoint.targetArtifactTypes] };
  if (input.realizedTimeRequired) return { ...base, status: "NOT_APPLICABLE", reason: "DEFERRED_TO_REALIZED_TIME", missingArtifacts: [] };
  if (input.notApplicable) return { ...base, status: "NOT_APPLICABLE", reason: "The source contract explicitly marks this checkpoint NOT_APPLICABLE.", missingArtifacts: [] };
  if (!checkpoint.sourceArtifactTypes.includes(input.sourceArtifact.artifactType) || !checkpoint.targetArtifactTypes.includes(input.targetArtifact.artifactType)) return { ...base, status: "NOT_READY", reason: "Artifact types do not match the checkpoint contract.", missingArtifacts: [] };
  if (input.notReady || checkpoint.implementationStatus !== "CONTRACT_READY") return { ...base, status: "NOT_READY", reason: "The checkpoint is not ready for execution.", missingArtifacts: [] };
  return { ...base, status: "APPLICABLE", reason: "The declared design-time source and target are available.", missingArtifacts: [] };
};
