import { entity, relation } from "./factories.mjs";
import { KNOWLEDGE_GRAPH_NAMESPACE } from "./schema.mjs";

const id = (family, slug) => `${KNOWLEDGE_GRAPH_NAMESPACE}:${family.toLowerCase()}:${slug}`;
const source = (sourceId) => [sourceId];

const modalities = [
  entity("Modality", "irm", "IRM", { aliases: ["MRI"], description: "Modalité nommée dans les contenus et projets NOXIA.", sourceRefs: source("source:irm") }),
  entity("Modality", "ct", "CT", { aliases: ["Scanner CT"], description: "Modalité nommée dans les contenus et projets NOXIA.", sourceRefs: source("source:ct") }),
];

const anatomy = [
  entity("BodySystem", "cardiovascular", "Système cardiovasculaire", { description: "Système anatomique cité par les contenus cardiaques NOXIA.", sourceRefs: source("source:corelab") }),
  entity("BodySystem", "nervous", "Système nerveux", { description: "Système anatomique cité par les contenus de neuro-imagerie NOXIA.", sourceRefs: source("source:perfusion-metabolic") }),
  entity("BodySystem", "respiratory", "Système respiratoire", { description: "Système anatomique cité par la démonstration CT thoracique.", sourceRefs: source("source:ct-viewer") }),
  entity("Organ", "heart", "Cœur", { aliases: ["Cardiaque"], description: "Organe cité dans les contenus d'IRM cardiaque et Core Lab.", sourceRefs: source("source:ecv") }),
  entity("Organ", "brain", "Cerveau", { aliases: ["Cérébral"], description: "Organe cité dans les contenus de perfusion et métabolisme cérébral.", sourceRefs: source("source:cmro2") }),
  entity("Organ", "lung", "Poumon", { aliases: ["Pulmonaire"], description: "Organe cité par la démonstration CT pneumologique.", sourceRefs: source("source:tools-viewer") }),
  entity("Region", "myocardium", "Myocarde", { description: "Région anatomique citée dans les publications et contenus cardiaques.", sourceRefs: source("source:publications") }),
  entity("Region", "cerebral", "Région cérébrale", { description: "Région anatomique utilisée par les contenus neurovasculaires.", sourceRefs: source("source:ct-perfusion") }),
  entity("Region", "thoracic", "Région thoracique", { description: "Région anatomique nommée dans la démonstration CT.", sourceRefs: source("source:ct-viewer") }),
];

const clinical = [
  entity("Disease", "acute-ischemic-stroke", "AVC ischémique aigu", { description: "Condition explicitement nommée dans les contenus de perfusion et les publications référencées.", sourceRefs: source("source:ct-perfusion") }),
  entity("Disease", "stemi", "Infarctus du myocarde avec sus-décalage du segment ST", { description: "Condition explicitement nommée dans le registre de publications affiché.", sourceRefs: source("source:publications") }),
  entity("Disease", "cerebral-tumoral-lesion", "Lésion tumorale cérébrale", { description: "Condition de démonstration explicitement nommée dans le projet de neuro-oncologie.", sourceRefs: source("source:projects") }),
  entity("ClinicalQuestion", "multicentric-quantification", "Quantification multicentrique", { description: "Question opérationnelle présente dans les contenus NOXIA ; elle n'encode pas de recommandation clinique.", sourceRefs: source("source:methodology") }),
  entity("ClinicalQuestion", "cardiac-tissue-characterization", "Caractérisation tissulaire cardiaque", { description: "Question méthodologique associée à ECV et mapping dans le dépôt.", sourceRefs: source("source:ecv") }),
  entity("ClinicalQuestion", "neurovascular-perfusion", "Quantification de la perfusion neurovasculaire", { description: "Question méthodologique associée à CBF, CBV et Tmax dans le dépôt.", sourceRefs: source("source:ct-perfusion") }),
];

const sequences = [
  entity("SequenceFamily", "late-enhancement", "Famille de rehaussement tardif", { description: "Famille de séquence citée par les contenus d'IRM cardiaque.", sourceRefs: source("source:irm") }),
  entity("SequenceFamily", "cardiac-mapping", "Famille de mapping cardiaque", { description: "Famille de séquence citée avec T1 et T2 dans les contenus cardiaques.", sourceRefs: source("source:ecv") }),
  entity("SequenceFamily", "perfusion", "Famille de perfusion", { description: "Famille de séquence ou d'acquisition citée dans les contenus CT et IRM.", sourceRefs: source("source:ct-perfusion") }),
  entity("SequenceFamily", "diffusion", "Famille de diffusion", { description: "Famille de séquence citée dans les contenus neurovasculaires.", sourceRefs: source("source:perfusion-metabolic") }),
  entity("SequenceFamily", "cardiac-cine", "Famille ciné cardiaque", { description: "Famille de séquence citée dans la démonstration d'IRM cardiaque.", sourceRefs: source("source:projects") }),
  entity("Sequence", "late-gadolinium-enhancement", "Late Gadolinium Enhancement — séquence", { aliases: ["LGE séquence"], description: "Séquence nommée dans les contenus d'IRM cardiaque.", sourceRefs: source("source:irm") }),
  entity("Sequence", "t1-mapping", "T1 mapping — séquence", { description: "Séquence nommée dans les contenus d'IRM quantitative.", sourceRefs: source("source:irm") }),
  entity("Sequence", "t2-mapping", "T2 mapping — séquence", { description: "Séquence nommée dans les contenus d'IRM quantitative.", sourceRefs: source("source:irm") }),
  entity("Sequence", "cardiac-cine", "Ciné cardiaque — séquence", { description: "Séquence nommée dans la démonstration d'IRM cardiaque.", sourceRefs: source("source:projects") }),
  entity("Sequence", "perfusion-ct", "CT perfusion — acquisition", { description: "Acquisition nommée par la page CT perfusion.", sourceRefs: source("source:ct-perfusion") }),
  entity("Sequence", "diffusion-mri", "Diffusion — séquence", { description: "Séquence citée dans les contenus de perfusion métabolique neuro.", sourceRefs: source("source:perfusion-metabolic") }),
];

const biomarkers = [
  entity("Biomarker", "ecv", "Volume extracellulaire", { aliases: ["ECV"], description: "Biomarqueur nommé dans les contenus cardiaques NOXIA.", sourceRefs: source("source:ecv") }),
  entity("Biomarker", "t1", "T1 natif", { description: "Biomarqueur nommé dans les contenus cardiaques NOXIA.", sourceRefs: source("source:ecv") }),
  entity("Biomarker", "t2", "T2 mapping", { description: "Biomarqueur nommé dans les contenus cardiaques NOXIA.", sourceRefs: source("source:ecv") }),
  entity("Biomarker", "lge-quantification", "Rehaussement tardif — quantification", { aliases: ["LGE quantification"], description: "Endpoint de quantification cité dans les contenus Core Lab.", sourceRefs: source("source:corelab") }),
  entity("Biomarker", "cbf", "Débit sanguin cérébral", { aliases: ["CBF"], description: "Biomarqueur nommé dans les contenus de perfusion.", sourceRefs: source("source:ct-perfusion") }),
  entity("Biomarker", "cbv", "Volume sanguin cérébral", { aliases: ["CBV"], description: "Biomarqueur nommé dans les contenus de perfusion.", sourceRefs: source("source:ct-perfusion") }),
  entity("Biomarker", "mtt", "Temps de transit moyen", { aliases: ["MTT"], description: "Biomarqueur nommé dans les contenus de perfusion.", sourceRefs: source("source:ct-perfusion") }),
  entity("Biomarker", "tmax", "Temps au maximum", { aliases: ["Tmax"], description: "Biomarqueur nommé dans les contenus de perfusion.", sourceRefs: source("source:ct-perfusion") }),
  entity("Biomarker", "oef", "Fraction d'extraction d'oxygène", { aliases: ["OEF"], description: "Biomarqueur nommé dans les contenus de métabolisme cérébral.", sourceRefs: source("source:oef") }),
  entity("Biomarker", "cmro2", "Consommation cérébrale d'oxygène", { aliases: ["CMRO2"], description: "Biomarqueur nommé dans les contenus de métabolisme cérébral.", sourceRefs: source("source:cmro2") }),
  entity("Biomarker", "adc", "Coefficient de diffusion apparent", { aliases: ["ADC"], description: "Biomarqueur nommé dans les contenus neurovasculaires.", sourceRefs: source("source:perfusion-metabolic") }),
  entity("Biomarker", "mvo", "Obstruction microvasculaire", { aliases: ["MVO"], description: "Biomarqueur nommé dans les contenus Core Lab cardiaques.", sourceRefs: source("source:corelab") }),
  entity("Biomarker", "myocardial-hemorrhage", "Hémorragie intramyocardique", { description: "Biomarqueur nommé dans le registre de publications affiché.", sourceRefs: source("source:publications") }),
];

const measurements = [
  entity("Measurement", "ecv", "Mesure ECV", { description: "Objet de mesure distinct, relié au biomarqueur ECV sans définir de seuil.", sourceRefs: source("source:ecv") }),
  entity("Measurement", "cbf", "Mesure CBF", { description: "Objet de mesure distinct, relié au biomarqueur CBF sans définir de seuil.", sourceRefs: source("source:ct-perfusion") }),
  entity("Measurement", "tmax", "Mesure Tmax", { description: "Objet de mesure distinct, relié au biomarqueur Tmax sans définir de seuil.", sourceRefs: source("source:ct-perfusion") }),
  entity("Measurement", "oef", "Mesure OEF", { description: "Objet de mesure distinct, relié au biomarqueur OEF sans règle clinique.", sourceRefs: source("source:oef") }),
  entity("Measurement", "cmro2", "Mesure CMRO2", { description: "Objet de mesure distinct, relié au biomarqueur CMRO2 sans règle clinique.", sourceRefs: source("source:cmro2") }),
];

const operations = [
  entity("Workflow", "dicom-audit", "Audit DICOM", { description: "Workflow cité pour contrôler géométrie, métadonnées et traçabilité.", sourceRefs: source("source:dicom") }),
  entity("Workflow", "corelab-cardiac-mri", "Workflow Core Lab IRM cardiaque", { description: "Workflow de lecture centralisée et de contrôle qualité décrit dans le dépôt.", sourceRefs: source("source:corelab") }),
  entity("Workflow", "multicentric-harmonization", "Harmonisation multicentrique", { description: "Workflow méthodologique cité pour IRM et CT.", sourceRefs: source("source:methodology") }),
  entity("Workflow", "quantitative-imaging", "Chaîne d'imagerie quantitative", { description: "Workflow du signal aux biomarqueurs décrit dans la page méthodologie.", sourceRefs: source("source:methodology") }),
  entity("Workflow", "dicom-anonymization", "Anonymisation DICOM", { description: "Étape de workflow explicitement citée dans l'analyse DICOM.", sourceRefs: source("source:dicom") }),
  entity("Workflow", "quality-control", "Contrôle qualité", { description: "Workflow transversal cité dans les contenus et viewers NOXIA.", sourceRefs: source("source:qc-viewer") }),
  entity("CoreLab", "noxia-cardiac-mri", "Core Lab IRM cardiovasculaire multicentrique", { description: "Capacité Core Lab explicitement présentée par NOXIA.", sourceRefs: source("source:corelab") }),
  entity("Pipeline", "dicom-to-nifti", "Pipeline de conversion DICOM vers NIfTI", { description: "Pipeline nommé dans l'analyse DICOM sans détail d'implémentation clinique.", sourceRefs: source("source:dicom") }),
  entity("Pipeline", "perfusion-segmentation-demo", "Pipeline de démonstration de segmentation de perfusion", { description: "Pipeline de démonstration décrit dans le catalogue projets.", sourceRefs: source("source:projects") }),
  entity("Pipeline", "multimodal-registration", "Pipeline de recalage multimodal", { description: "Pipeline de recalage rigide et affine décrit dans le catalogue projets.", sourceRefs: source("source:projects") }),
  entity("Pipeline", "neuro-oncology-segmentation", "Pipeline de segmentation neuro-oncologique", { description: "Pipeline de démonstration décrit dans le catalogue projets.", sourceRefs: source("source:projects") }),
  entity("Pipeline", "cardiac-quantification-demo", "Pipeline de démonstration de quantification cardiaque", { description: "Pipeline de démonstration décrit dans le catalogue projets.", sourceRefs: source("source:projects") }),
  entity("Pipeline", "ct-quantification-demo", "Pipeline de démonstration de quantification CT", { description: "Pipeline de démonstration décrit dans le catalogue projets.", sourceRefs: source("source:projects") }),
];

const viewers = [
  entity("Viewer", "cardiac", "CardiacViewer", { description: "Composant de visualisation cardiaque présent dans le dépôt.", sourceRefs: source("source:cardiac-viewer") }),
  entity("Viewer", "ct-scan", "CTScanViewer", { description: "Composant de visualisation CT présent dans le dépôt.", sourceRefs: source("source:ct-viewer") }),
  entity("Viewer", "neuro-oncology", "NeuroOncoViewer", { description: "Composant de visualisation neuro-oncologique présent dans le dépôt.", sourceRefs: source("source:neuro-viewer") }),
  entity("Viewer", "perfusion-segmentation", "PerfusionSegmentationViewer", { description: "Composant de visualisation de perfusion et segmentation présent dans le dépôt.", sourceRefs: source("source:perfusion-viewer") }),
  entity("Viewer", "quality-control", "QCViewer", { description: "Composant de contrôle qualité présent dans le dépôt.", sourceRefs: source("source:qc-viewer") }),
  entity("Viewer", "registration", "RegistrationViewer", { description: "Composant de visualisation du recalage présent dans le dépôt.", sourceRefs: source("source:registration-viewer") }),
  entity("Viewer", "slice", "SliceViewer", { description: "Composant de visualisation de coupes présent dans le dépôt.", sourceRefs: source("source:slice-viewer") }),
  entity("Viewer", "tools", "OutilsViewer", { description: "Composant de démonstration d'outils sur mesure présent dans le dépôt.", sourceRefs: source("source:tools-viewer") }),
];

const projects = [
  entity("ResearchProject", "perfusion-segmentation", "Perfusion cérébrale CT/IRM", { description: "Projet de démonstration présent dans le catalogue NOXIA.", sourceRefs: source("source:projects") }),
  entity("ResearchProject", "neuro-onco", "Neuro-oncologie IRM", { description: "Projet de démonstration présent dans le catalogue NOXIA.", sourceRefs: source("source:projects") }),
  entity("ResearchProject", "recalage", "Recalage IRM / CT", { description: "Projet de démonstration présent dans le catalogue NOXIA.", sourceRefs: source("source:projects") }),
  entity("ResearchProject", "cardiac", "IRM cardiaque", { description: "Projet de démonstration présent dans le catalogue NOXIA.", sourceRefs: source("source:projects") }),
  entity("ResearchProject", "ct-scan", "Analyse CT quantitative", { description: "Projet de démonstration présent dans le catalogue NOXIA.", sourceRefs: source("source:projects") }),
  entity("ResearchProject", "tools", "Outils sur mesure", { description: "Projet de démonstration présent dans le catalogue NOXIA.", sourceRefs: source("source:projects") }),
  entity("Study", "rhu-marvelous", "RHU MARVELOUS", { description: "Étude ou contribution Core Lab listée dans les références NOXIA.", sourceRefs: source("source:publications") }),
  entity("Study", "mimi", "MIMI", { description: "Étude listée dans les références NOXIA avec une contribution méthodologique.", sourceRefs: source("source:publications") }),
  entity("Study", "covert-mi", "COVERT-MI — étude", { description: "Étude listée dans les publications affichées NOXIA ; le suffixe désambiguïse cette identité de la publication homonyme.", sourceRefs: source("source:publications") }),
];

const publications = [
  entity("Publication", "pone-0161855", "Shear-Wave Elastography Assessments of Quadriceps Stiffness Changes prior to, during and after Prolonged Exercise: A Longitudinal Study during an Extreme Mountain Ultra-Marathon", { description: "Publication listée dans le registre NOXIA.", sourceRefs: source("source:publications"), properties: { doi: "10.1371/journal.pone.0161855", pmid: null, authors: null, journal: "PLoS ONE", year: 2016, publicationType: "unspecified", evidenceLevel: "UNKNOWN" } }),
  entity("Publication", "pone-0167668", "Correction: Shear-Wave Elastography Assessments of Quadriceps Stiffness Changes prior to, during and after Prolonged Exercise", { description: "Publication de correction listée dans le registre NOXIA.", sourceRefs: source("source:publications"), properties: { doi: "10.1371/journal.pone.0167668", pmid: null, authors: null, journal: "PLoS ONE", year: 2016, publicationType: "correction", evidenceLevel: "UNKNOWN" } }),
  entity("Publication", "pone-0245684", "Association of myocardial hemorrhage and persistent microvascular obstruction with circulating inflammatory biomarkers in STEMI patients", { description: "Publication listée dans le registre NOXIA.", sourceRefs: source("source:publications"), properties: { doi: "10.1371/journal.pone.0245684", pmid: null, authors: null, journal: "PLoS ONE", year: 2021, publicationType: "unspecified", evidenceLevel: "UNKNOWN" } }),
  entity("Publication", "stnfr-stemi", "Serum Soluble Tumor Necrosis Factor Receptors 1 and 2 Are Early Prognosis Markers After ST-Segment Elevation Myocardial Infarction", { description: "Publication listée sans DOI ou PMID dans le registre NOXIA.", sourceRefs: source("source:publications"), properties: { doi: null, pmid: null, authors: null, journal: "Frontiers in Pharmacology", year: 2021, publicationType: "unspecified", evidenceLevel: "UNKNOWN" } }),
  entity("Publication", "stroke-124-047311", "Oxygen Extraction Fraction Mapping on Admission Magnetic Resonance Imaging May Predict Recovery of Hyperacute Ischemic Brain Lesions After Successful Thrombectomy: A Retrospective Observational Study", { description: "Publication listée dans le registre NOXIA.", sourceRefs: source("source:publications"), properties: { doi: "10.1161/STROKEAHA.124.047311", pmid: null, authors: null, journal: "Stroke", year: 2024, publicationType: "retrospective-observational-study", evidenceLevel: "UNKNOWN" } }),
  entity("Publication", "biorxiv-2024-12-12", "Collaterals influence oxygen metabolism on admission MRI in acute ischemic stroke", { description: "Preprint listé dans le registre NOXIA.", sourceRefs: source("source:publications"), evidenceStatus: "PRELIMINARY", properties: { doi: "10.1101/2024.12.12.24318960", pmid: null, authors: null, journal: "Preprint", year: 2024, publicationType: "preprint", evidenceLevel: "PRELIMINARY" } }),
  entity("Publication", "covert-mi", "COVERT-MI — publication record", { description: "Publication ou étude listée dans le registre NOXIA sans DOI ou PMID ; le suffixe désambiguïse cette identité de l'étude homonyme.", sourceRefs: source("source:publications"), properties: { doi: null, pmid: null, authors: null, journal: "Circulation", year: 2021, publicationType: "unspecified", evidenceLevel: "UNKNOWN" } }),
  entity("Publication", "inflammation-penumbra", "Inflammation biomarkers & penumbra mismatch in acute ischemic stroke", { description: "Publication listée dans le registre NOXIA sans DOI ou PMID.", sourceRefs: source("source:publications"), properties: { doi: null, pmid: null, authors: null, journal: "Neurology", year: 2022, publicationType: "unspecified", evidenceLevel: "UNKNOWN" } }),
  entity("Publication", "mimi-003388", "Belle L et al. Circ Cardiovasc Interv. 2016;9(3):e003388.", { description: "Référence de contribution méthodologique listée dans le registre NOXIA.", sourceRefs: source("source:publications"), properties: { doi: "10.1161/CIRCINTERVENTIONS.115.003388", pmid: null, authors: "Belle L et al.", journal: "Circ Cardiovasc Interv.", year: 2016, publicationType: "unspecified", evidenceLevel: "UNKNOWN" } }),
];

const knowledgeSupport = [
  entity("Guideline", "scmr-cardiac-mri-standardisation", "SCMR Guidelines — Standardisation IRM cardiaque", { description: "Mention de guideline conservée avec référence bibliographique incomplète dans le dépôt.", sourceRefs: source("source:segmentation"), status: "unresolved_reference" }),
  entity("Recommendation", "eacvi-biomarker-reproducibility", "Recommandations EACVI sur la reproductibilité des biomarqueurs", { description: "Mention de recommandation conservée avec référence bibliographique incomplète dans le dépôt.", sourceRefs: source("source:segmentation"), status: "unresolved_reference" }),
  entity("Format", "dicom", "DICOM — format", { description: "Format d'imagerie explicitement traité par les contenus NOXIA.", sourceRefs: source("source:dicom") }),
  entity("Format", "nifti", "NIfTI", { description: "Format de conversion et de masque explicitement cité par les contenus NOXIA.", sourceRefs: source("source:dicom") }),
  entity("Format", "dicom-seg", "DICOM SEG", { description: "Format de segmentation explicitement cité dans les contenus NOXIA.", sourceRefs: source("source:segmentation") }),
  entity("Standard", "dicom", "DICOM — standard reference", { description: "Standard explicitement cité dans les contenus NOXIA ; sa fiche officielle reste à relier avant toute qualification STANDARD.", sourceRefs: source("source:dicom") }),
  entity("Terminology", "dicom-tags", "Tags DICOM", { description: "Terme technique explicitement cité par les contenus d'audit DICOM.", sourceRefs: source("source:dicom") }),
  entity("Definition", "quantitative-biomarker", "Définition opérationnelle de biomarqueur quantitatif", { description: "Définition opérationnelle dérivée du texte méthodologique interne, non d'une norme externe.", sourceRefs: source("source:methodology") }),
  entity("Synonym", "core-lab", "CoreLab / Core Lab", { description: "Variante orthographique attestée dans le dépôt.", sourceRefs: source("source:services"), properties: { terms: ["CoreLab", "Core Lab"] } }),
  entity("Synonym", "late-enhancement", "Late Gadolinium Enhancement / rehaussement tardif", { description: "Variantes terminologiques attestées dans le dépôt dans un contexte de séquence cardiaque.", sourceRefs: source("source:irm"), properties: { terms: ["Late Gadolinium Enhancement", "rehaussement tardif"] } }),
  entity("Abbreviation", "ecv", "ECV — abbreviation record", { description: "Abréviation liée au volume extracellulaire dans les contenus NOXIA.", sourceRefs: source("source:ecv"), properties: { term: "ECV", expandedEntityId: id("Biomarker", "ecv") } }),
  entity("Abbreviation", "cbf", "CBF — abbreviation record", { description: "Abréviation liée au débit sanguin cérébral dans les contenus NOXIA.", sourceRefs: source("source:ct-perfusion"), properties: { term: "CBF", expandedEntityId: id("Biomarker", "cbf") } }),
  entity("Abbreviation", "cbv", "CBV — abbreviation record", { description: "Abréviation liée au volume sanguin cérébral dans les contenus NOXIA.", sourceRefs: source("source:ct-perfusion"), properties: { term: "CBV", expandedEntityId: id("Biomarker", "cbv") } }),
  entity("Abbreviation", "mtt", "MTT — abbreviation record", { description: "Abréviation liée au temps de transit moyen dans les contenus NOXIA.", sourceRefs: source("source:ct-perfusion"), properties: { term: "MTT", expandedEntityId: id("Biomarker", "mtt") } }),
  entity("Abbreviation", "oef", "OEF — abbreviation record", { description: "Abréviation liée à la fraction d'extraction d'oxygène dans les contenus NOXIA.", sourceRefs: source("source:oef"), properties: { term: "OEF", expandedEntityId: id("Biomarker", "oef") } }),
  entity("Abbreviation", "cmro2", "CMRO2 — abbreviation record", { description: "Abréviation liée à la consommation cérébrale d'oxygène dans les contenus NOXIA.", sourceRefs: source("source:cmro2"), properties: { term: "CMRO2", expandedEntityId: id("Biomarker", "cmro2") } }),
  entity("Tool", "python", "Python", { description: "Outil cité dans le catalogue projets NOXIA.", sourceRefs: source("source:projects") }),
  entity("Tool", "nibabel", "NiBabel", { description: "Outil cité dans le catalogue projets NOXIA.", sourceRefs: source("source:projects") }),
  entity("Tool", "numpy", "NumPy", { description: "Outil cité dans le catalogue projets NOXIA.", sourceRefs: source("source:projects") }),
  entity("Tool", "matplotlib", "Matplotlib", { description: "Outil cité dans le catalogue projets NOXIA.", sourceRefs: source("source:projects") }),
  entity("Tool", "react", "React", { description: "Outil cité dans le catalogue projets NOXIA.", sourceRefs: source("source:projects") }),
  entity("Tool", "simpleitk", "SimpleITK", { description: "Outil cité dans le catalogue projets NOXIA.", sourceRefs: source("source:projects") }),
  entity("Tool", "antspy", "ANTsPy", { description: "Outil cité dans le catalogue projets NOXIA.", sourceRefs: source("source:projects") }),
  entity("Tool", "elastix", "Elastix", { description: "Outil cité dans le catalogue projets NOXIA.", sourceRefs: source("source:projects") }),
  entity("Service", "corelab", "Service Core Lab IRM / CT", { description: "Service explicitement présenté par NOXIA.", sourceRefs: source("source:services") }),
  entity("Service", "dicom-audit", "Service d'audit DICOM", { description: "Service explicitement présenté par NOXIA.", sourceRefs: source("source:services") }),
  entity("Service", "multicentric-harmonization", "Service d'harmonisation multicentrique", { description: "Service explicitement présenté par NOXIA.", sourceRefs: source("source:services") }),
  entity("Service", "quantitative-engineering", "Service d'ingénierie quantitative", { description: "Service explicitement présenté par NOXIA.", sourceRefs: source("source:services") }),
  entity("Feature", "slice-navigation", "Navigation de coupes", { description: "Fonctionnalité déclarée par les viewers de coupes et de perfusion.", sourceRefs: source("source:slice-viewer") }),
  entity("Feature", "mask-overlay", "Superposition de masques", { description: "Fonctionnalité déclarée par les viewers de perfusion et de neuro-oncologie.", sourceRefs: source("source:perfusion-viewer") }),
  entity("Feature", "windowing", "Fenêtrage", { description: "Fonctionnalité déclarée par les composants de visualisation d'images.", sourceRefs: source("source:qc-viewer") }),
  entity("Feature", "registration-comparison", "Comparaison de recalage", { description: "Fonctionnalité déclarée par le viewer de recalage.", sourceRefs: source("source:registration-viewer") }),
  entity("Feature", "quality-control", "Contrôle qualité visuel", { description: "Fonctionnalité déclarée par le viewer de contrôle qualité.", sourceRefs: source("source:qc-viewer") }),
];

export const entities = Object.freeze([
  ...modalities,
  ...anatomy,
  ...clinical,
  ...sequences,
  ...biomarkers,
  ...measurements,
  ...operations,
  ...viewers,
  ...projects,
  ...publications,
  ...knowledgeSupport,
]);

const r = (type, fromFamily, fromSlug, toFamily, toSlug, sourceRef, description) => relation(
  type,
  id(fromFamily, fromSlug),
  id(toFamily, toSlug),
  { sourceRefs: source(sourceRef), description },
);

export const relations = Object.freeze([
  r("PART_OF", "Organ", "heart", "BodySystem", "cardiovascular", "source:corelab", "Le cœur est rattaché au système cardiovasculaire dans le modèle anatomique."),
  r("PART_OF", "Organ", "brain", "BodySystem", "nervous", "source:cmro2", "Le cerveau est rattaché au système nerveux dans le modèle anatomique."),
  r("PART_OF", "Organ", "lung", "BodySystem", "respiratory", "source:ct-viewer", "Le poumon est rattaché au système respiratoire dans le modèle anatomique."),
  r("PART_OF", "Region", "myocardium", "Organ", "heart", "source:publications", "Le myocarde est rattaché au cœur dans le modèle anatomique."),
  r("PART_OF", "Region", "cerebral", "Organ", "brain", "source:ct-perfusion", "La région cérébrale est rattachée au cerveau dans le modèle anatomique."),
  r("PART_OF", "Region", "thoracic", "Organ", "lung", "source:ct-viewer", "La région thoracique est rattachée au poumon dans le périmètre de la démonstration CT."),
  r("USES", "Sequence", "late-gadolinium-enhancement", "Modality", "irm", "source:irm", "La séquence de rehaussement tardif est citée dans le contexte IRM."),
  r("USES", "Sequence", "t1-mapping", "Modality", "irm", "source:irm", "Le T1 mapping est cité dans le contexte IRM."),
  r("USES", "Sequence", "t2-mapping", "Modality", "irm", "source:irm", "Le T2 mapping est cité dans le contexte IRM."),
  r("USES", "Sequence", "cardiac-cine", "Modality", "irm", "source:projects", "La ciné cardiaque est citée dans le contexte IRM."),
  r("USES", "Sequence", "perfusion-ct", "Modality", "ct", "source:ct-perfusion", "La CT perfusion est citée dans le contexte CT."),
  r("USES", "Sequence", "diffusion-mri", "Modality", "irm", "source:perfusion-metabolic", "La diffusion est citée dans le contexte IRM."),
  r("PART_OF", "Sequence", "late-gadolinium-enhancement", "SequenceFamily", "late-enhancement", "source:irm", "La séquence est rattachée à sa famille de rehaussement tardif."),
  r("PART_OF", "Sequence", "t1-mapping", "SequenceFamily", "cardiac-mapping", "source:ecv", "La séquence est rattachée à la famille de mapping cardiaque."),
  r("PART_OF", "Sequence", "t2-mapping", "SequenceFamily", "cardiac-mapping", "source:ecv", "La séquence est rattachée à la famille de mapping cardiaque."),
  r("PART_OF", "Sequence", "cardiac-cine", "SequenceFamily", "cardiac-cine", "source:projects", "La séquence est rattachée à sa famille ciné cardiaque."),
  r("PART_OF", "Sequence", "perfusion-ct", "SequenceFamily", "perfusion", "source:ct-perfusion", "L'acquisition est rattachée à la famille de perfusion."),
  r("PART_OF", "Sequence", "diffusion-mri", "SequenceFamily", "diffusion", "source:perfusion-metabolic", "La séquence est rattachée à la famille de diffusion."),
  r("MEASURES", "Sequence", "t1-mapping", "Biomarker", "t1", "source:ecv", "Le contenu associe la séquence T1 mapping au biomarqueur T1."),
  r("MEASURES", "Sequence", "t2-mapping", "Biomarker", "t2", "source:ecv", "Le contenu associe la séquence T2 mapping au biomarqueur T2."),
  r("MEASURES", "Sequence", "late-gadolinium-enhancement", "Biomarker", "lge-quantification", "source:corelab", "Le contenu associe la séquence de rehaussement tardif à la quantification LGE."),
  r("MEASURES", "Sequence", "perfusion-ct", "Biomarker", "cbf", "source:ct-perfusion", "Le contenu associe la CT perfusion au biomarqueur CBF."),
  r("MEASURES", "Sequence", "perfusion-ct", "Biomarker", "cbv", "source:ct-perfusion", "Le contenu associe la CT perfusion au biomarqueur CBV."),
  r("MEASURES", "Sequence", "perfusion-ct", "Biomarker", "tmax", "source:ct-perfusion", "Le contenu associe la CT perfusion au biomarqueur Tmax."),
  r("APPLIES_TO", "Biomarker", "ecv", "Organ", "heart", "source:ecv", "Le contenu ECV est dans le domaine cardiaque."),
  r("APPLIES_TO", "Biomarker", "t1", "Organ", "heart", "source:ecv", "Le contenu T1 mapping est dans le domaine cardiaque."),
  r("APPLIES_TO", "Biomarker", "t2", "Organ", "heart", "source:ecv", "Le contenu T2 mapping est dans le domaine cardiaque."),
  r("APPLIES_TO", "Biomarker", "cbf", "Organ", "brain", "source:ct-perfusion", "Le contenu CBF est dans le domaine cérébral."),
  r("APPLIES_TO", "Biomarker", "cbv", "Organ", "brain", "source:ct-perfusion", "Le contenu CBV est dans le domaine cérébral."),
  r("APPLIES_TO", "Biomarker", "tmax", "Organ", "brain", "source:ct-perfusion", "Le contenu Tmax est dans le domaine cérébral."),
  r("APPLIES_TO", "Biomarker", "oef", "Organ", "brain", "source:oef", "Le contenu OEF est dans le domaine cérébral."),
  r("APPLIES_TO", "Biomarker", "cmro2", "Organ", "brain", "source:cmro2", "Le contenu CMRO2 est dans le domaine cérébral."),
  r("DERIVED_FROM", "Measurement", "ecv", "Biomarker", "ecv", "source:ecv", "La mesure ECV est dérivée du biomarqueur ECV dans le modèle."),
  r("DERIVED_FROM", "Measurement", "cbf", "Biomarker", "cbf", "source:ct-perfusion", "La mesure CBF est dérivée du biomarqueur CBF dans le modèle."),
  r("DERIVED_FROM", "Measurement", "tmax", "Biomarker", "tmax", "source:ct-perfusion", "La mesure Tmax est dérivée du biomarqueur Tmax dans le modèle."),
  r("DERIVED_FROM", "Measurement", "oef", "Biomarker", "oef", "source:oef", "La mesure OEF est dérivée du biomarqueur OEF dans le modèle."),
  r("DERIVED_FROM", "Measurement", "cmro2", "Biomarker", "cmro2", "source:cmro2", "La mesure CMRO2 est dérivée du biomarqueur CMRO2 dans le modèle."),
  r("USES", "Workflow", "dicom-audit", "Format", "dicom", "source:dicom", "L'audit DICOM consomme le format DICOM."),
  r("USES", "Workflow", "dicom-anonymization", "Format", "dicom", "source:dicom", "L'anonymisation décrite est appliquée à DICOM."),
  r("USES", "Workflow", "corelab-cardiac-mri", "Workflow", "dicom-audit", "source:corelab", "Le workflow Core Lab commence par la qualification DICOM."),
  r("USES", "Workflow", "quantitative-imaging", "Workflow", "quality-control", "source:methodology", "La chaîne quantitative inclut du contrôle qualité."),
  r("SUPPORTS", "Workflow", "multicentric-harmonization", "ClinicalQuestion", "multicentric-quantification", "source:methodology", "L'harmonisation soutient la quantification multicentrique."),
  r("IMPLEMENTED_BY", "CoreLab", "noxia-cardiac-mri", "Workflow", "corelab-cardiac-mri", "source:corelab", "Le Core Lab est relié à son workflow explicite."),
  r("IMPLEMENTED_BY", "Pipeline", "dicom-to-nifti", "Workflow", "dicom-audit", "source:dicom", "La conversion est une étape du workflow d'audit DICOM."),
  r("PRODUCES", "Pipeline", "perfusion-segmentation-demo", "Measurement", "cbf", "source:projects", "La démonstration traite des cartes de perfusion incluant CBF."),
  r("PRODUCES", "Pipeline", "perfusion-segmentation-demo", "Measurement", "tmax", "source:projects", "La démonstration traite des cartes de perfusion incluant Tmax."),
  r("SUPPORTS", "Viewer", "perfusion-segmentation", "Pipeline", "perfusion-segmentation-demo", "source:perfusion-viewer", "Le viewer soutient la démonstration de perfusion et segmentation."),
  r("SUPPORTS", "Viewer", "quality-control", "Workflow", "quality-control", "source:qc-viewer", "Le viewer soutient le contrôle qualité visuel."),
  r("SUPPORTS", "Viewer", "registration", "Pipeline", "multimodal-registration", "source:registration-viewer", "Le viewer soutient le pipeline de recalage."),
  r("SUPPORTS", "Viewer", "neuro-oncology", "Pipeline", "neuro-oncology-segmentation", "source:neuro-viewer", "Le viewer soutient la démonstration de segmentation neuro-oncologique."),
  r("SUPPORTS", "Viewer", "cardiac", "Pipeline", "cardiac-quantification-demo", "source:cardiac-viewer", "Le viewer soutient la démonstration de quantification cardiaque."),
  r("SUPPORTS", "Viewer", "ct-scan", "Pipeline", "ct-quantification-demo", "source:ct-viewer", "Le viewer soutient la démonstration de quantification CT."),
  r("HAS_FEATURE", "Viewer", "quality-control", "Feature", "windowing", "source:qc-viewer", "Le viewer QC expose le fenêtrage."),
  r("HAS_FEATURE", "Viewer", "quality-control", "Feature", "quality-control", "source:qc-viewer", "Le viewer QC expose un contrôle qualité visuel."),
  r("HAS_FEATURE", "Viewer", "perfusion-segmentation", "Feature", "mask-overlay", "source:perfusion-viewer", "Le viewer de perfusion expose la superposition de masques."),
  r("HAS_FEATURE", "Viewer", "registration", "Feature", "registration-comparison", "source:registration-viewer", "Le viewer de recalage expose une comparaison de recalage."),
  r("HAS_FEATURE", "Viewer", "slice", "Feature", "slice-navigation", "source:slice-viewer", "Le viewer de coupes expose la navigation de coupes."),
  r("IMPLEMENTED_BY", "ResearchProject", "perfusion-segmentation", "Pipeline", "perfusion-segmentation-demo", "source:projects", "Le projet est relié à son pipeline de démonstration."),
  r("IMPLEMENTED_BY", "ResearchProject", "neuro-onco", "Pipeline", "neuro-oncology-segmentation", "source:projects", "Le projet est relié à son pipeline de démonstration."),
  r("IMPLEMENTED_BY", "ResearchProject", "recalage", "Pipeline", "multimodal-registration", "source:projects", "Le projet est relié à son pipeline de démonstration."),
  r("IMPLEMENTED_BY", "ResearchProject", "cardiac", "Pipeline", "cardiac-quantification-demo", "source:projects", "Le projet est relié à son pipeline de démonstration."),
  r("IMPLEMENTED_BY", "ResearchProject", "ct-scan", "Pipeline", "ct-quantification-demo", "source:projects", "Le projet est relié à son pipeline de démonstration."),
  r("USES", "Pipeline", "perfusion-segmentation-demo", "Tool", "python", "source:projects", "Le catalogue projets cite Python pour ce périmètre de démonstration."),
  r("USES", "Pipeline", "perfusion-segmentation-demo", "Tool", "nibabel", "source:projects", "Le catalogue projets cite NiBabel pour ce périmètre de démonstration."),
  r("USES", "Pipeline", "multimodal-registration", "Tool", "antspy", "source:projects", "Le catalogue projets cite ANTsPy pour ce périmètre de démonstration."),
  r("USES", "Pipeline", "multimodal-registration", "Tool", "elastix", "source:projects", "Le catalogue projets cite Elastix pour ce périmètre de démonstration."),
  r("USES", "Pipeline", "ct-quantification-demo", "Tool", "simpleitk", "source:projects", "Le catalogue projets cite SimpleITK pour ce périmètre de démonstration."),
  r("SUPPORTS", "Service", "corelab", "CoreLab", "noxia-cardiac-mri", "source:services", "Le service Core Lab soutient le Core Lab du modèle."),
  r("SUPPORTS", "Service", "dicom-audit", "Workflow", "dicom-audit", "source:services", "Le service d'audit soutient le workflow d'audit DICOM."),
  r("SUPPORTS", "Service", "multicentric-harmonization", "Workflow", "multicentric-harmonization", "source:services", "Le service soutient le workflow d'harmonisation."),
  r("SUPPORTS", "Service", "quantitative-engineering", "Workflow", "quantitative-imaging", "source:services", "Le service soutient la chaîne d'imagerie quantitative."),
  r("COMPATIBLE_WITH", "Format", "dicom", "Standard", "dicom", "source:dicom", "Le format DICOM est rattaché au standard DICOM dans le modèle."),
  r("REFERENCES", "Terminology", "dicom-tags", "Format", "dicom", "source:dicom", "La terminologie des tags est rattachée au format DICOM."),
  r("REFERENCES", "Abbreviation", "ecv", "Biomarker", "ecv", "source:ecv", "L'abréviation ECV est rattachée à son biomarqueur canonique."),
  r("REFERENCES", "Abbreviation", "cbf", "Biomarker", "cbf", "source:ct-perfusion", "L'abréviation CBF est rattachée à son biomarqueur canonique."),
  r("REFERENCES", "Abbreviation", "cbv", "Biomarker", "cbv", "source:ct-perfusion", "L'abréviation CBV est rattachée à son biomarqueur canonique."),
  r("REFERENCES", "Abbreviation", "mtt", "Biomarker", "mtt", "source:ct-perfusion", "L'abréviation MTT est rattachée à son biomarqueur canonique."),
  r("REFERENCES", "Abbreviation", "oef", "Biomarker", "oef", "source:oef", "L'abréviation OEF est rattachée à son biomarqueur canonique."),
  r("REFERENCES", "Abbreviation", "cmro2", "Biomarker", "cmro2", "source:cmro2", "L'abréviation CMRO2 est rattachée à son biomarqueur canonique."),
  r("REFERENCES", "Synonym", "core-lab", "CoreLab", "noxia-cardiac-mri", "source:services", "La variante terminologique CoreLab / Core Lab est rattachée au Core Lab canonique."),
  r("REFERENCES", "Synonym", "late-enhancement", "Sequence", "late-gadolinium-enhancement", "source:irm", "La variante terminologique est rattachée à la séquence canonique."),
  r("DOCUMENTS", "Publication", "stroke-124-047311", "Biomarker", "oef", "source:publications", "La publication cite l'OEF dans son titre."),
  r("DOCUMENTS", "Publication", "biorxiv-2024-12-12", "Biomarker", "cmro2", "source:publications", "Le preprint cite le métabolisme de l'oxygène dans son titre."),
  r("DOCUMENTS", "Publication", "pone-0245684", "Biomarker", "myocardial-hemorrhage", "source:publications", "La publication cite l'hémorragie myocardique dans son titre."),
  r("DOCUMENTS", "Publication", "pone-0245684", "Biomarker", "mvo", "source:publications", "La publication cite l'obstruction microvasculaire dans son titre."),
  r("APPLIES_TO", "Publication", "stroke-124-047311", "Disease", "acute-ischemic-stroke", "source:publications", "La publication cite les lésions ischémiques aiguës dans son titre."),
  r("APPLIES_TO", "Publication", "biorxiv-2024-12-12", "Disease", "acute-ischemic-stroke", "source:publications", "Le preprint cite l'AVC ischémique aigu dans son titre."),
  r("APPLIES_TO", "Publication", "pone-0245684", "Disease", "stemi", "source:publications", "La publication cite STEMI dans son titre."),
  r("REFERENCES", "Guideline", "scmr-cardiac-mri-standardisation", "SequenceFamily", "cardiac-mapping", "source:segmentation", "La guideline mentionnée concerne LGE et mapping cardiaque."),
  r("REFERENCES", "Recommendation", "eacvi-biomarker-reproducibility", "Biomarker", "ecv", "source:segmentation", "La recommandation mentionnée concerne la reproductibilité de biomarqueurs, dont ECV dans ce contexte de source."),
  r("SUPPORTS", "Study", "rhu-marvelous", "CoreLab", "noxia-cardiac-mri", "source:publications", "La contribution RHU est décrite dans un contexte Core Lab."),
  r("SUPPORTS", "Study", "mimi", "CoreLab", "noxia-cardiac-mri", "source:publications", "La contribution MIMI est décrite dans un contexte d'analyse IRM Core Lab."),
  r("RELATED_TO", "Study", "covert-mi", "Publication", "covert-mi", "source:publications", "L'étude et l'entrée de publication partagent la même mention source, sans fusionner leurs identités."),
]);
